INSERT INTO test.mstb_query_groupby (GROUPBY_ID,QUERY_ID,TABLE_NAME,FIELD_NAME,ORDER_NO,RECORD_STATE,CREATED_USER_ID,CREATED_TIME,UPDATED_USER_ID,UPDATED_TIME) VALUES 
('22','461','sa','SHOP_CODE',10,1,NULL,NULL,NULL,NULL)
,('42','342','t','MODULE_CODE',10,1,NULL,NULL,NULL,NULL)
;