INSERT INTO test.mstb_query_button (BUTTON_ID,QUERY_ID,BUTTON_NO,BUTTON_NAME,SUB_URL,EXECUTE_JS,ORDER_NO,RECORD_STATE,CREATED_USER_ID,CREATED_TIME,UPDATED_USER_ID,UPDATED_TIME,OPEN_TYPE) VALUES 
('100001','100003','add','add',NULL,NULL,10,1,NULL,NULL,NULL,NULL,0)
,('100003','100005','kgem_root_km_klist_initAdd','增加','knowledgeAction!initAdd.action',NULL,10,1,NULL,NULL,NULL,NULL,0)
,('100005','100005','kgem_root_km_klist_initModify','修改','knowledgeAction!initModify.action','checkModify(1)',20,1,NULL,NULL,NULL,NULL,0)
,('100007','100005','kgem_root_km_klist_delete','删除','knowledgeAction!delete.action','checkDelete(1)',30,1,NULL,NULL,NULL,NULL,1)
,('100014','100006','addButton','增加','query/query.jsp?oprt=initAdd',NULL,10,1,NULL,NULL,NULL,NULL,0)
,('100016','100006','deleteButton','删除','baseAction!delete.action','checkDelete(1)',20,1,NULL,NULL,NULL,NULL,1)
,('100018','100006','modifyButton','修改','query/query.jsp?oprt=initModify','checkModify(1)',30,1,NULL,NULL,NULL,NULL,0)
,('100020','100006','testButton','测试',NULL,'checkModify(1)',40,1,NULL,NULL,NULL,NULL,1)
,('100022','100006','copyButton','复制','baseAction!copyQueryInput.action','checkModify(1)',50,1,NULL,NULL,NULL,NULL,0)
,('100028','100012','sysManage_application_initModify','修改','applicationAction!initModify.action','checkModify(1)',30,1,NULL,NULL,NULL,NULL,0)
;
INSERT INTO test.mstb_query_button (BUTTON_ID,QUERY_ID,BUTTON_NO,BUTTON_NAME,SUB_URL,EXECUTE_JS,ORDER_NO,RECORD_STATE,CREATED_USER_ID,CREATED_TIME,UPDATED_USER_ID,UPDATED_TIME,OPEN_TYPE) VALUES 
('100030','100012','sysManage_application_addAppPlus','增加扩展应用','applicationPlusAction!initAdd.action','checkAdd(1,1)',40,1,NULL,NULL,NULL,NULL,0)
,('100032','100014','sysManage_module_initAdd0','增加当前级','moduleAction!initAdd.action?moduleVo.addLevel=0',NULL,10,1,NULL,NULL,NULL,NULL,0)
,('100034','100014','sysManage_module_initAdd1','增加下一级','moduleAction!initAdd.action?moduleVo.addLevel=1','checkAdd(1, 1)',20,1,NULL,NULL,NULL,NULL,0)
,('100036','100014','sysManage_module_initModify','修改','moduleAction!initModify.action','checkModify(1)',30,1,NULL,NULL,NULL,NULL,0)
,('100038','100014','sysManage_module_delete','删除','moduleAction!delete.action','checkDelete(1)',40,1,NULL,NULL,NULL,NULL,1)
,('100040','100018','sysManage_role_initAdd','增加','roleAction!initAdd.action',NULL,10,1,NULL,NULL,NULL,NULL,0)
,('100042','100018','sysManage_role_delete','删除','roleAction!delete.action','checkDelete(1)',20,1,NULL,NULL,NULL,NULL,1)
,('100044','100018','sysManage_role_initModify','修改','roleAction!initModify.action','checkModify(1)',30,1,NULL,NULL,NULL,NULL,0)
,('100046','100022','sysManage_applicationPlus_delete','删除','applicationPlusAction!delete.action','checkDelete(1)',20,1,NULL,NULL,NULL,NULL,1)
,('100048','100022','sysManage_applicationPlus_modify','修改','applicationPlusAction!initModify.action','checkModify(1)',30,1,NULL,NULL,NULL,NULL,0)
;
INSERT INTO test.mstb_query_button (BUTTON_ID,QUERY_ID,BUTTON_NO,BUTTON_NAME,SUB_URL,EXECUTE_JS,ORDER_NO,RECORD_STATE,CREATED_USER_ID,CREATED_TIME,UPDATED_USER_ID,UPDATED_TIME,OPEN_TYPE) VALUES 
('100050','100024','sysManage_emailTemplate_initAdd','增加','emailTemplateAction!initAdd.action',NULL,10,1,NULL,NULL,NULL,NULL,0)
,('100052','100024','sysManage_emailTemplate_delete','删除','emailTemplateAction!delete.action','checkDelete(1)',20,1,NULL,NULL,NULL,NULL,1)
,('100054','100024','sysManage_emailTemplate_initModify','修改','emailTemplateAction!initModify.action','checkModify(1)',30,1,NULL,NULL,NULL,NULL,0)
,('100056','100026','sysManage_smsTemplate_initAdd','增加','smsTemplateAction!initAdd.action',NULL,10,1,NULL,NULL,NULL,NULL,0)
,('100058','100026','sysManage_smsTemplate_delete','删除','smsTemplateAction!delete.action','checkDelete(1)',20,1,NULL,NULL,NULL,NULL,1)
,('100060','100026','sysManage_smsTemplate_initModify','修改','smsTemplateAction!initModify.action','checkModify(1)',30,1,NULL,NULL,NULL,NULL,0)
,('100062','100028','sysManage_schemainfor_initAdd','增加','bdsSchemaInforAction!initAdd.action',NULL,10,1,NULL,NULL,NULL,NULL,0)
,('100064','100028','sysManage_schemainfor_delete','删除','bdsSchemaInforAction!delete.action','checkDelete(1)',20,1,NULL,NULL,NULL,NULL,1)
,('100066','100028','sysManage_schemainfor_initModify','修改','bdsSchemaInforAction!initModify.action','checkModify(1)',30,1,NULL,NULL,NULL,NULL,0)
,('100068','100032','add','增加','timeingJobAction!initAdd.action',NULL,10,1,NULL,NULL,NULL,NULL,0)
;
INSERT INTO test.mstb_query_button (BUTTON_ID,QUERY_ID,BUTTON_NO,BUTTON_NAME,SUB_URL,EXECUTE_JS,ORDER_NO,RECORD_STATE,CREATED_USER_ID,CREATED_TIME,UPDATED_USER_ID,UPDATED_TIME,OPEN_TYPE) VALUES 
('100070','100032','delete','删除','timeingJobAction!delete.action','checkDelete(1)',20,1,NULL,NULL,NULL,NULL,1)
,('100072','100032','modify','修改','timeingJobAction!initModify.action','checkModify(1)',30,1,NULL,NULL,NULL,NULL,0)
,('100074','100032','reset','重置','timeingJobAction!reset.action','checkDelete(1)',40,1,NULL,NULL,NULL,NULL,1)
,('100076','100034','add','增加','reportInfoAction!initAdd.action',NULL,10,1,NULL,NULL,NULL,NULL,0)
,('100078','100034','delete','删除','reportInfoAction!delete.action','checkDelete(1)',20,1,NULL,NULL,NULL,NULL,1)
,('100080','100034','modify','修改','reportInfoAction!initModify.action','checkModify(1)',30,1,NULL,NULL,NULL,NULL,0)
,('1002','885','PRA_PRAISE_LIST_FINAL_DELETE','删除(勾选记录)','praiseListAction!delete.action','checkDelete(1)',10,1,NULL,NULL,NULL,NULL,1)
,('102','163','ebooking_baseParameter_add','新增','EbBaseParameterAction!initAdd.action',NULL,10,1,NULL,NULL,NULL,NULL,0)
,('1022','981','SENDER_EMAIL_ADD','添加','initEmailSettingAdd.action',NULL,10,1,NULL,NULL,NULL,NULL,0)
,('1023','981','SENDER_EMAIL_MODIFY','修改','initEmailSettingModify.action','checkModify(1)',20,1,NULL,NULL,NULL,NULL,0)
;
INSERT INTO test.mstb_query_button (BUTTON_ID,QUERY_ID,BUTTON_NO,BUTTON_NAME,SUB_URL,EXECUTE_JS,ORDER_NO,RECORD_STATE,CREATED_USER_ID,CREATED_TIME,UPDATED_USER_ID,UPDATED_TIME,OPEN_TYPE) VALUES 
('103','164','ebooking_location_add','新增','EbLocationAction!initAdd.action',NULL,10,1,NULL,NULL,NULL,NULL,0)
,('104','164','ebooking_location_modify','修改','EbLocationAction!initMdf.action','checkModify(1)',20,1,NULL,NULL,NULL,NULL,0)
,('1042','2','copyButton','复制','baseAction!copyQueryInput.action','checkModify(1)',50,1,NULL,NULL,NULL,NULL,0)
,('1043','1061','cr_shopBacklog_checkReturn_initAdd','新增','checkReturnAction!initAdd.action',NULL,1,1,NULL,NULL,NULL,NULL,4)
,('105','164','ebooking_location_del','删除','EbLocationAction!delete.action','checkDelete(1)',30,1,NULL,NULL,NULL,NULL,1)
,('106','165','ebooking_equipment_add','新增','EbEquipmentAction!initAdd.action',NULL,10,1,NULL,NULL,NULL,NULL,0)
,('107','165','ebooking_equipment_modify','修改','EbEquipmentAction!initMdf.action','checkModify(1)',20,1,NULL,NULL,NULL,NULL,0)
,('108','165','ebooking_equipment_del','删除','EbEquipmentAction!delete.action','checkDelete(1)',30,1,NULL,NULL,NULL,NULL,1)
,('110','167','sysManage_applicationPlus_delete','删除','applicationPlusAction!delete.action','checkDelete(1)',20,1,NULL,NULL,NULL,NULL,1)
,('1104','1141','ft_financeBacklog_back','返回主页',NULL,'window.parent.parent.location = window.parent.parent.location;',10,1,NULL,NULL,NULL,NULL,NULL)
;
INSERT INTO test.mstb_query_button (BUTTON_ID,QUERY_ID,BUTTON_NO,BUTTON_NAME,SUB_URL,EXECUTE_JS,ORDER_NO,RECORD_STATE,CREATED_USER_ID,CREATED_TIME,UPDATED_USER_ID,UPDATED_TIME,OPEN_TYPE) VALUES 
('111','167','sysManage_applicationPlus_modify','修改','applicationPlusAction!initModify.action','checkModify(1)',30,1,NULL,NULL,NULL,NULL,0)
,('112','168','sysManage_blackList_initAdd','增加','blackListAction!initAdd.action',NULL,10,1,NULL,NULL,NULL,NULL,0)
,('1123','170','rf_batchCancel','批量删除','bankRefundAction!batchCancel.action  ','checkBatchCancel()',22,1,NULL,NULL,NULL,NULL,4)
,('113','168','sysManage_blackList_delete','删除','blackListAction!delete.action','checkDelete(1)',20,1,NULL,NULL,NULL,NULL,1)
,('114','169','rf_batchComplete','批量完成','bankRefundAction!batchComplete.action','checkDelete(1);',1,1,NULL,NULL,NULL,NULL,4)
,('115','170','rf_eBankingList','导出网银清单','excelOperateAction!exportEbankingList.action','checkDelete(1);',1,1,NULL,NULL,NULL,NULL,4)
,('116','170','rf_generateCertificate','生成凭证','excelOperateAction!generateCertificate.action','checkDelete(1);',2,1,NULL,NULL,NULL,NULL,4)
,('1166','1124','cr_commQuery_exportEbankingList','导出网银清单','excelOperateAction!exportEbankingList.action','checkDelete(1);',1,1,NULL,NULL,NULL,NULL,4)
,('1167','1124','cr_commQuery_generateCertificate','生成凭证','excelOperateAction!generateCertificate.action','checkDelete(1);',2,1,NULL,NULL,NULL,NULL,4)
,('1168','1124','cr_commQuery_requery','重新查询','checkReturn/crCommonQuery.jsp',NULL,3,1,NULL,NULL,NULL,NULL,4)
;
INSERT INTO test.mstb_query_button (BUTTON_ID,QUERY_ID,BUTTON_NO,BUTTON_NAME,SUB_URL,EXECUTE_JS,ORDER_NO,RECORD_STATE,CREATED_USER_ID,CREATED_TIME,UPDATED_USER_ID,UPDATED_TIME,OPEN_TYPE) VALUES 
('1169','1125','rf_eBankingList','导出网银清单','excelOperateAction!exportEbankingList.action','checkDelete(1);',1,1,NULL,NULL,NULL,NULL,4)
,('1170','1125','rf_generateCertificate','生成凭证','excelOperateAction!generateCertificate.action','checkDelete(1);',2,1,NULL,NULL,NULL,NULL,4)
,('1171','1125','rf_commQuery_reQuery','重新查询','showTwoPageAction.action?queryCode=bank_comm_query_tp',NULL,12,1,NULL,NULL,NULL,NULL,4)
,('1172','1125','rf_batchCancel','批量删除','bankRefundAction!batchCancel.action  ','checkBatchCancel()',22,1,NULL,NULL,NULL,NULL,4)
,('1183','1821','mi_link','操作指引',NULL,'window.open(''http://cnacclwp-docinfodb.intranet.local/cms/docInfo%21view.action?id=201308011107172126'')',60,1,NULL,NULL,NULL,NULL,NULL)
,('123','141','sysManage_application_addAppPlus','增加扩展应用','applicationPlusAction!initAdd.action','checkAdd(1,1)',40,1,NULL,NULL,NULL,NULL,0)
,('124','181','sysManage_emailTemplate_initAdd','增加','emailTemplateAction!initAdd.action',NULL,10,1,NULL,NULL,NULL,NULL,0)
,('125','181','sysManage_emailTemplate_delete','删除','emailTemplateAction!delete.action','checkDelete(1)',20,1,NULL,NULL,NULL,NULL,1)
,('126','181','sysManage_emailTemplate_initModify','修改','emailTemplateAction!initModify.action','checkModify(1)',30,1,NULL,NULL,NULL,NULL,0)
,('142','201','sysManage_schemainfor_initAdd','增加','bdsSchemaInforAction!initAdd.action',NULL,10,1,NULL,NULL,NULL,NULL,0)
;
INSERT INTO test.mstb_query_button (BUTTON_ID,QUERY_ID,BUTTON_NO,BUTTON_NAME,SUB_URL,EXECUTE_JS,ORDER_NO,RECORD_STATE,CREATED_USER_ID,CREATED_TIME,UPDATED_USER_ID,UPDATED_TIME,OPEN_TYPE) VALUES 
('143','201','sysManage_schemainfor_delete','删除','bdsSchemaInforAction!delete.action','checkDelete(1)',20,1,NULL,NULL,NULL,NULL,1)
,('144','201','sysManage_schemainfor_initModify','修改','bdsSchemaInforAction!initModify.action','checkModify(1)',30,1,NULL,NULL,NULL,NULL,0)
,('162','241','sysManage_userProfile_initAdd','增加','userProfileAction!initAdd.action',NULL,10,1,NULL,NULL,NULL,NULL,0)
,('162622','1341','mi_add','增加','printInfoAction!initAdd.action',NULL,10,1,NULL,NULL,NULL,NULL,0)
,('162623','1341','mi_delete','删除','printInfoAction!delete.action','checkDelete(1)',20,1,NULL,NULL,NULL,NULL,1)
,('162624','1341','mi_modify','修改','printInfoAction!initModify.action','checkModify(1)',30,1,NULL,NULL,NULL,NULL,0)
,('162625','1341','mi_print_ord','打印清单','printInfoAction!printOrd.action','checkDelete(1)',40,1,NULL,NULL,NULL,NULL,0)
,('162626','1341','mi_print_sign','打印签收单','printInfoAction!printSign.action','checkDelete(1)',50,1,NULL,NULL,NULL,NULL,0)
,('162642','1401','mi_add','增加','printInfoAction!initAdd.action',NULL,10,1,NULL,NULL,NULL,NULL,0)
,('162643','1401','mi_delete','删除','printInfoAction!delete.action','checkDelete(1)',20,1,NULL,NULL,NULL,NULL,1)
;
INSERT INTO test.mstb_query_button (BUTTON_ID,QUERY_ID,BUTTON_NO,BUTTON_NAME,SUB_URL,EXECUTE_JS,ORDER_NO,RECORD_STATE,CREATED_USER_ID,CREATED_TIME,UPDATED_USER_ID,UPDATED_TIME,OPEN_TYPE) VALUES 
('162644','1401','mi_modify','修改','printInfoAction!initModify.action','checkModify(1)',30,1,NULL,NULL,NULL,NULL,0)
,('162645','1401','mi_print_ord','打印清单','printInfoAction!printOrd.action','checkDelete(1)',40,1,NULL,NULL,NULL,NULL,0)
,('162646','1401','mi_print_sign','打印签收单','printInfoAction!printSign.action','checkDelete(1)',50,1,NULL,NULL,NULL,NULL,0)
,('162702','1481','rf_eBankingList','导出网银清单','../refund/excelOperateAction!exportEbankingList.action','checkDelete(1);',1,1,NULL,NULL,NULL,NULL,4)
,('162703','1481','rf_generateCertificate','生成凭证','../refund/excelOperateAction!generateCertificate.action','checkDelete(1);',2,1,NULL,NULL,NULL,NULL,4)
,('162704','1481','rf_commQuery_reQuery','重新查询','../sysManage/showTwoPageAction.action?queryCode=bank_custom_query',NULL,12,1,NULL,NULL,NULL,NULL,4)
,('162705','1481','rf_batchCancel','批量删除','../refund/bankRefundAction!batchCancel.action','checkBatchCancel()',22,1,NULL,NULL,NULL,NULL,4)
,('162872','1703','mi_add','增加','printInfoAction!initAdd.action',NULL,10,1,NULL,NULL,NULL,NULL,0)
,('162873','1703','mi_delete','删除','printInfoAction!delete.action','checkDelete(1)',20,1,NULL,NULL,NULL,NULL,1)
,('162874','1703','mi_modify','修改','printInfoAction!initModify.action','checkModify(1)',30,1,NULL,NULL,NULL,NULL,0)
;
INSERT INTO test.mstb_query_button (BUTTON_ID,QUERY_ID,BUTTON_NO,BUTTON_NAME,SUB_URL,EXECUTE_JS,ORDER_NO,RECORD_STATE,CREATED_USER_ID,CREATED_TIME,UPDATED_USER_ID,UPDATED_TIME,OPEN_TYPE) VALUES 
('162875','1703','mi_print_ord','打印清单','printInfoAction!printOrd.action','checkDelete(1)',40,1,NULL,NULL,NULL,NULL,0)
,('162876','1703','mi_print_sign','打印签收单','printInfoAction!printSign.action','checkDelete(1)',50,1,NULL,NULL,NULL,NULL,0)
,('162902','1821','mi_add','增加','printInfoAction!initAdd.action',NULL,10,1,NULL,NULL,NULL,NULL,0)
,('162903','1821','mi_delete','删除','printInfoAction!delete.action','checkDelete(1)',20,1,NULL,NULL,NULL,NULL,1)
,('162904','1821','mi_modify','修改','printInfoAction!initModify.action','checkModify(1)',30,1,NULL,NULL,NULL,NULL,0)
,('162905','1821','mi_print_ord','打印清单','printInfoAction!printOrd.action','checkDelete(1)',40,1,NULL,NULL,NULL,NULL,0)
,('162906','1821','mi_print_sign','打印签收单','printInfoAction!printSign.action','checkDelete(1)',50,1,NULL,NULL,NULL,NULL,0)
,('162922','1923','mi_add','增加','printInfoAction!initAdd.action',NULL,10,1,NULL,NULL,NULL,NULL,0)
,('162923','1923','mi_delete','删除','printInfoAction!delete.action','checkDelete(1)',20,1,NULL,NULL,NULL,NULL,1)
,('162924','1923','mi_modify','修改','printInfoAction!initModify.action','checkModify(1)',30,1,NULL,NULL,NULL,NULL,0)
;
INSERT INTO test.mstb_query_button (BUTTON_ID,QUERY_ID,BUTTON_NO,BUTTON_NAME,SUB_URL,EXECUTE_JS,ORDER_NO,RECORD_STATE,CREATED_USER_ID,CREATED_TIME,UPDATED_USER_ID,UPDATED_TIME,OPEN_TYPE) VALUES 
('162925','1923','mi_print_ord','打印清单','printInfoAction!printOrd.action','checkDelete(1)',40,1,NULL,NULL,NULL,NULL,0)
,('162926','1923','mi_print_sign','打印签收单','printInfoAction!printSign.action','checkDelete(1)',50,1,NULL,NULL,NULL,NULL,0)
,('162942','2001','mi_add','增加','printInfoAction!initAdd.action',NULL,10,1,NULL,NULL,NULL,NULL,0)
,('162943','2001','mi_delete','删除','printInfoAction!delete.action','checkDelete(1)',20,1,NULL,NULL,NULL,NULL,1)
,('162944','2001','mi_modify','修改','printInfoAction!initModify.action','checkModify(1)',30,1,NULL,NULL,NULL,NULL,0)
,('162945','2001','mi_print_ord','打印清单','printInfoAction!printOrd.action','checkDelete(1)',40,1,NULL,NULL,NULL,NULL,0)
,('162946','2001','mi_print_sign','打印签收单','printInfoAction!printSign.action','checkDelete(1)',50,1,NULL,NULL,NULL,NULL,0)
,('163','241','sysManage_userProfile_delete','删除','userProfileAction!delete.action','checkDelete(1)',20,1,NULL,NULL,NULL,NULL,1)
,('164','241','sysManage_userProfile_initModify','修改','userProfileAction!initModify.action','checkModify(1)',30,1,NULL,NULL,NULL,NULL,0)
,('165','241','sysManage_userProfile_resetPwd','重置密码','userProfileAction!resetPwd.action','checkModify(1)',40,1,NULL,NULL,NULL,NULL,1)
;
INSERT INTO test.mstb_query_button (BUTTON_ID,QUERY_ID,BUTTON_NO,BUTTON_NAME,SUB_URL,EXECUTE_JS,ORDER_NO,RECORD_STATE,CREATED_USER_ID,CREATED_TIME,UPDATED_USER_ID,UPDATED_TIME,OPEN_TYPE) VALUES 
('166','223','cr_shopBacklog_checkReturn_initAdd','新增','checkReturnAction!initAdd.action',NULL,1,1,NULL,NULL,NULL,NULL,4)
,('182','261','sysManage_smsTemplate_initAdd','增加','smsTemplateAction!initAdd.action',NULL,10,1,NULL,NULL,NULL,NULL,0)
,('183','261','sysManage_smsTemplate_delete','删除','smsTemplateAction!delete.action','checkDelete(1)',20,1,NULL,NULL,NULL,NULL,1)
,('184','261','sysManage_smsTemplate_initModify','修改','smsTemplateAction!initModify.action','checkModify(1)',30,1,NULL,NULL,NULL,NULL,0)
,('185','262','cr_commQuery_exportEbankingList','导出网银清单','excelOperateAction!exportEbankingList.action','checkDelete(1);',1,1,NULL,NULL,NULL,NULL,4)
,('186','262','cr_commQuery_generateCertificate','生成凭证','excelOperateAction!generateCertificate.action','checkDelete(1);',2,1,NULL,NULL,NULL,NULL,4)
,('200742','200761','br_dic_shopMgt_add_button','增加','shopMgtAction!initAdd.action',NULL,10,1,NULL,NULL,NULL,NULL,0)
,('200743','200761','br_dic_shopMgt_modify_button','更新','shopMgtAction!initModify.action','checkModify(1)',20,1,NULL,NULL,NULL,NULL,0)
,('200744','200761','br_dic_shopMgt_bmodify_button','批量更新','shopMgtAction!initBatchModify.action',NULL,30,1,NULL,NULL,NULL,NULL,0)
,('200762','200781','br_dic_rateMgt_add_button','增加','rateMgtAction!initAdd.action',NULL,10,1,NULL,NULL,NULL,NULL,0)
;
INSERT INTO test.mstb_query_button (BUTTON_ID,QUERY_ID,BUTTON_NO,BUTTON_NAME,SUB_URL,EXECUTE_JS,ORDER_NO,RECORD_STATE,CREATED_USER_ID,CREATED_TIME,UPDATED_USER_ID,UPDATED_TIME,OPEN_TYPE) VALUES 
('200763','200781','br_dic_rateMgt_modify_button','更新','rateMgtAction!initModify.action','checkModify(1)',20,1,NULL,NULL,NULL,NULL,0)
,('200764','200781','br_dic_rateMgt_bmodify_button','批量更新','rateMgtAction!initBatchModify.action',NULL,30,1,NULL,NULL,NULL,NULL,0)
,('200782','200803','br_biz_detail_report_button_delete','删除工作项','reconDetailReportAction!deleteReconDetailReportTask.action','checkDelete(1)',10,1,NULL,NULL,NULL,NULL,1)
,('200842','201001','br_dic_bankMgt_add_button','增加','bankMgtAction!initAdd.action',NULL,10,1,NULL,NULL,NULL,NULL,0)
,('200843','201001','br_dic_bankMgt_modify_button','更新','bankMgtAction!initModify.action','checkModify(1)',20,1,NULL,NULL,NULL,NULL,0)
,('201008','201296','delete_upload_report_dept','删除','reportUploadAction!logicDeleteReport.action','checkDelete(1);if(!ret){return false} ret = checkAllDisabled()',30,1,NULL,NULL,NULL,NULL,1)
,('201009','201307','DeleteTempCode','删除','reportCodeAction!deleteTempCode.action','checkDelete(1)',60,1,NULL,NULL,NULL,NULL,1)
,('201010','201307','EditReportType','更改报表类型','reportCodeAction!initUpdateTempCodeOfType.action','checkDelete(1)',40,1,NULL,NULL,NULL,NULL,0)
,('201011','201307','EditUnitName','更改区/店/部','reportCodeAction!initUpdateTempCodeOfName.action','checkDelete(1)',50,1,NULL,NULL,NULL,NULL,0)
,('201012','201300','delete_upload_report_area','删除','reportUploadAction!logicDeleteReport.action','checkDelete(1);if(!ret){return false} ret = checkAllDisabled()',30,1,NULL,NULL,NULL,NULL,1)
;
INSERT INTO test.mstb_query_button (BUTTON_ID,QUERY_ID,BUTTON_NO,BUTTON_NAME,SUB_URL,EXECUTE_JS,ORDER_NO,RECORD_STATE,CREATED_USER_ID,CREATED_TIME,UPDATED_USER_ID,UPDATED_TIME,OPEN_TYPE) VALUES 
('201013','201297','delete_upload_report_shop','删除','reportUploadAction!logicDeleteReport.action','checkDelete(1);if(!ret){return false} ret = checkAllDisabled()',30,1,NULL,NULL,NULL,NULL,1)
,('201014','201306','NewReportType','新建类型','reportTypeAction!initAdd.action',NULL,10,1,NULL,NULL,NULL,NULL,0)
,('201015','201299','multi_report_upload','批量上传','reportUploadAction!toMultiReportUpload.action',NULL,10,1,NULL,NULL,NULL,NULL,0)
,('201016','201299','report_upload','单份上传','reportUploadAction!toReportUpload.action',NULL,20,1,NULL,NULL,NULL,NULL,0)
,('201017','201306','DeleteReportType','删除','reportTypeAction!delete.action','checkDelete(1)',20,1,NULL,NULL,NULL,NULL,4)
,('201018','201299','delete_upload_report','删除','reportUploadAction!logicDeleteReport.action','checkDelete(1);if(!ret){return false} ret = checkAllDisabled()',30,1,NULL,NULL,NULL,NULL,1)
,('201020','201304','multi_report_upload_for_finance','批量上传','reportUploadAction!toMultiReportUpload.action',NULL,10,1,NULL,NULL,NULL,NULL,0)
,('201021','201304','report_upload_for_finance','单份上传','reportUploadAction!toReportUpload.action',NULL,20,1,NULL,NULL,NULL,NULL,0)
,('201022','201304','delete_upload_report_for_finance','删除','reportUploadAction!logicDeleteReport.action','checkDelete(1)',30,1,NULL,NULL,NULL,NULL,1)
,('201023','201302','multi_report_upload_area_for_finance','批量上传','reportUploadAction!toMultiReportUpload.action',NULL,10,1,NULL,NULL,NULL,NULL,0)
;
INSERT INTO test.mstb_query_button (BUTTON_ID,QUERY_ID,BUTTON_NO,BUTTON_NAME,SUB_URL,EXECUTE_JS,ORDER_NO,RECORD_STATE,CREATED_USER_ID,CREATED_TIME,UPDATED_USER_ID,UPDATED_TIME,OPEN_TYPE) VALUES 
('201024','201302','report_upload_area_for_finance','单份上传','reportUploadAction!toReportUpload.action',NULL,20,1,NULL,NULL,NULL,NULL,0)
,('201025','201302','delete_upload_report_area_for_finance','删除','reportUploadAction!logicDeleteReport.action','checkDelete(1)',30,1,NULL,NULL,NULL,NULL,1)
,('201026','201303','multi_report_upload_dept_for_finance','批量上传','reportUploadAction!toMultiReportUpload.action',NULL,10,1,NULL,NULL,NULL,NULL,0)
,('201027','201303','report_upload_dept_for_finance','单份上传','reportUploadAction!toReportUpload.action',NULL,20,1,NULL,NULL,NULL,NULL,0)
,('201028','201303','delete_upload_report_dept_for_finance','删除','reportUploadAction!logicDeleteReport.action','checkDelete(1)',30,1,NULL,NULL,NULL,NULL,1)
,('201029','201305','multi_report_upload_shop_for_finance','批量上传','reportUploadAction!toMultiReportUpload.action',NULL,10,1,NULL,NULL,NULL,NULL,0)
,('201030','201305','report_upload_shop_for_finance','单份上传','reportUploadAction!toReportUpload.action',NULL,20,1,NULL,NULL,NULL,NULL,0)
,('201031','201305','delete_upload_report_shop_for_finance','删除','reportUploadAction!logicDeleteReport.action','checkDelete(1)',30,1,NULL,NULL,NULL,NULL,1)
,('201032','201296','multi_report_upload_dept','批量上传','reportUploadAction!toMultiReportUpload.action',NULL,10,1,NULL,NULL,NULL,NULL,0)
,('201033','201296','report_upload_dept','单份上传','reportUploadAction!toReportUpload.action',NULL,20,1,NULL,NULL,NULL,NULL,0)
;
INSERT INTO test.mstb_query_button (BUTTON_ID,QUERY_ID,BUTTON_NO,BUTTON_NAME,SUB_URL,EXECUTE_JS,ORDER_NO,RECORD_STATE,CREATED_USER_ID,CREATED_TIME,UPDATED_USER_ID,UPDATED_TIME,OPEN_TYPE) VALUES 
('201034','201301','fr_report_code_initAdd','新建代码','reportCodeAction!initAdd.action',NULL,10,1,NULL,NULL,NULL,NULL,0)
,('201035','201301','DeleteReportCode','删除','reportCodeAction!delete.action','checkDelete(1)',20,1,NULL,NULL,NULL,NULL,4)
,('201036','201301','CopyReportCode','复制','reportCodeAction!copyReportCode.action','checkDelete(1)',30,1,NULL,NULL,NULL,NULL,1)
,('201037','201300','multi_report_upload_area','批量上传','reportUploadAction!toMultiReportUpload.action',NULL,10,1,NULL,NULL,NULL,NULL,0)
,('201038','201300','report_upload_area','单份上传','reportUploadAction!toReportUpload.action',NULL,20,1,NULL,NULL,NULL,NULL,0)
,('201039','201297','multi_report_upload_shop','批量上传','reportUploadAction!toMultiReportUpload.action',NULL,10,1,NULL,NULL,NULL,NULL,0)
,('201040','201297','report_upload_shop','单份上传','reportUploadAction!toReportUpload.action',NULL,20,1,NULL,NULL,NULL,NULL,0)
,('201041','201309','upload_log_delete','删除','reportUploadAction!logicDeleteLog.action','checkDelete(1)',10,1,NULL,NULL,NULL,NULL,1)
,('201042','201334','Global_Recogniton_Delete','Delete','globalRecognitionAction!delete.action','checkDelete(1)',20,1,NULL,NULL,NULL,NULL,1)
,('201043','201334','Global_Recogniton_Search','Search','fcShowAction.action?queryCode=Global_Recogniton',NULL,30,1,NULL,NULL,NULL,NULL,4)
;
INSERT INTO test.mstb_query_button (BUTTON_ID,QUERY_ID,BUTTON_NO,BUTTON_NAME,SUB_URL,EXECUTE_JS,ORDER_NO,RECORD_STATE,CREATED_USER_ID,CREATED_TIME,UPDATED_USER_ID,UPDATED_TIME,OPEN_TYPE) VALUES 
('201044','201334','Global_Recogniton_Add','Add','globalRecognitionAction!initAdd.action',NULL,10,1,NULL,NULL,NULL,NULL,0)
,('201045','1081','Contact_Record_EDIT','Edit','pubContactAction!initModify.action','checkModify(1)',20,1,NULL,NULL,NULL,NULL,0)
,('201046','1081','Contact_Record_ADD','Add','pubContactAction!initAdd.action',NULL,10,1,NULL,NULL,NULL,NULL,0)
,('201047','1081','Import_Contact_Record','Upload','fcSystem/contactRecord/import_excel.jsp',NULL,40,1,NULL,NULL,NULL,NULL,0)
,('201048','1081','Contact_Record_delete','Delete','pubContactAction!delete.action','checkDelete(1)',25,1,NULL,NULL,NULL,NULL,1)
,('201049','1081','Contact_Record_SEARCH','Search','showAction.action?queryCode=FC_Contact_Record',NULL,30,1,NULL,NULL,NULL,NULL,4)
,('201050','1082','FC_List_Upload_Import','Import FC List','fcSystem/fcList/import_excel.jsp',NULL,10,1,NULL,NULL,NULL,NULL,0)
,('201051','1121','Contact_Record_ADD','Add','pubContactAction!initAdd.action',NULL,10,1,NULL,NULL,NULL,NULL,0)
,('201052','1121','Contact_Record_delete','Delete','pubContactAction!delete.action','checkDelete(1)',30,1,NULL,NULL,NULL,NULL,1)
,('201053','1121','Contact_Record_SEARCH_ALL','Search','fcShowAction.action?queryCode=FC_Contact_Record_ALL',NULL,40,1,NULL,NULL,NULL,NULL,4)
;
INSERT INTO test.mstb_query_button (BUTTON_ID,QUERY_ID,BUTTON_NO,BUTTON_NAME,SUB_URL,EXECUTE_JS,ORDER_NO,RECORD_STATE,CREATED_USER_ID,CREATED_TIME,UPDATED_USER_ID,UPDATED_TIME,OPEN_TYPE) VALUES 
('201054','1121','Import_Contact_Record','Upload','fcSystem/contactRecord/import_excel.jsp',NULL,50,1,NULL,NULL,NULL,NULL,0)
,('201055','201311','roleDelUser','删除用户','fcRoleUserAction!delete.action',NULL,20,1,NULL,NULL,NULL,NULL,1)
,('201056','201311','roleAddUser','增加用户','fcRoleUserAction!initAdd.action',NULL,10,1,NULL,NULL,NULL,NULL,0)
,('201057','201347','mt_listDetailShop_returnQueryPage','重新查询','showMeetingTicketAction!init.action?queryCode=mt_listDetailShop',NULL,20,1,NULL,NULL,NULL,NULL,4)
,('202','281','cr_bankAccount_add','增加','bankAccountAction!initAdd.action',NULL,1,1,NULL,NULL,NULL,NULL,0)
,('203','281','cr_bankAccount_modify','修改','bankAccountAction!initModify.action','checkModify(1);',2,1,NULL,NULL,NULL,NULL,0)
,('204','281','cr_bankAccount_delete','删除','bankAccountAction!delete.action','checkDelete(1);',3,1,NULL,NULL,NULL,NULL,1)
,('205','282','cr_shopCoda_modify','修改','shopCodaAction!initModify.action','checkModify(1);',2,1,NULL,NULL,NULL,NULL,0)
,('206','282','cr_shopCoda_delete','删除','shopCodaAction!delete.action','checkDelete(1);',3,1,NULL,NULL,NULL,NULL,1)
,('207','282','cr_shopCoda_add','新增','shopCodaAction!initAdd.action',NULL,1,1,NULL,NULL,NULL,NULL,0)
;
INSERT INTO test.mstb_query_button (BUTTON_ID,QUERY_ID,BUTTON_NO,BUTTON_NAME,SUB_URL,EXECUTE_JS,ORDER_NO,RECORD_STATE,CREATED_USER_ID,CREATED_TIME,UPDATED_USER_ID,UPDATED_TIME,OPEN_TYPE) VALUES 
('23','41','sysManage_exception_initAdd','增加','exceptionCfgAction!initAdd.action',NULL,10,1,NULL,NULL,NULL,NULL,0)
,('24','41','sysManage_exception_initModify','修改','exceptionCfgAction!initModify.action','checkModify(1)',30,1,NULL,NULL,NULL,NULL,0)
,('242','82','ebooking_blackList_del','删除','EbBlacklistAction!delete.action','checkDelete(1)',20,1,NULL,NULL,NULL,NULL,1)
,('25','41','sysManage_exception_delete','删除','exceptionCfgAction!delete.action','checkDelete(1)',20,1,NULL,NULL,NULL,NULL,1)
,('262','342','test2','test2',NULL,NULL,20,1,NULL,NULL,NULL,NULL,NULL)
,('263','342','test','test','http://www.google.com',NULL,10,1,NULL,NULL,NULL,NULL,0)
,('286','301','mt_financeBacklog_initModify_batchComplete','批量完成','meetingTicketAction!batchComplete.action','checkDelete(1)',10,1,NULL,NULL,NULL,NULL,1)
,('3','2','addButton','增加','query/query.jsp?oprt=initAdd',NULL,10,1,NULL,NULL,NULL,NULL,0)
,('303','381','mt_listDetail_returnQueryPage','重新查询','showMeetingTicketAction!init.action?queryCode=mt_listDetail',NULL,20,1,NULL,NULL,NULL,NULL,4)
,('304','383','cr_financeBacklog_batchComplete','批量完成','checkReturnAction!batchComplete.action','checkDelete(1);',1,1,NULL,NULL,NULL,NULL,4)
;
INSERT INTO test.mstb_query_button (BUTTON_ID,QUERY_ID,BUTTON_NO,BUTTON_NAME,SUB_URL,EXECUTE_JS,ORDER_NO,RECORD_STATE,CREATED_USER_ID,CREATED_TIME,UPDATED_USER_ID,UPDATED_TIME,OPEN_TYPE) VALUES 
('322','401','mt_listStatistics_returnQueryPage','重新查询','showMeetingTicketAction!init.action?queryCode=mt_listStatistics',NULL,20,1,NULL,NULL,NULL,NULL,4)
,('325','402','mt_listDetailShop_returnQueryPage','重新查询','showMeetingTicketAction!init.action?queryCode=mt_listDetailShop',NULL,20,1,NULL,NULL,NULL,NULL,4)
,('327','404','add','增加','reportInfoAction!initAdd.action',NULL,10,1,NULL,NULL,NULL,NULL,0)
,('328','404','delete','删除','reportInfoAction!delete.action','checkDelete(1)',20,1,NULL,NULL,NULL,NULL,1)
,('329','404','modify','修改','reportInfoAction!initModify.action','checkModify(1)',30,1,NULL,NULL,NULL,NULL,0)
,('331','405','add','增加','reportSqlAction!initAdd.action',NULL,10,1,NULL,NULL,NULL,NULL,0)
,('332','405','delete','删除','reportSqlAction!delete.action','checkDelete(1)',20,1,NULL,NULL,NULL,NULL,1)
,('333','405','modify','修改','reportSqlAction!initModify.action','checkModify(1)',30,1,NULL,NULL,NULL,NULL,0)
,('334','406','add','增加','reportParaAction!initAdd.action',NULL,10,1,NULL,NULL,NULL,NULL,0)
,('335','406','delete','删除','reportParaAction!delete.action','checkDelete(1)',20,1,NULL,NULL,NULL,NULL,1)
;
INSERT INTO test.mstb_query_button (BUTTON_ID,QUERY_ID,BUTTON_NO,BUTTON_NAME,SUB_URL,EXECUTE_JS,ORDER_NO,RECORD_STATE,CREATED_USER_ID,CREATED_TIME,UPDATED_USER_ID,UPDATED_TIME,OPEN_TYPE) VALUES 
('336','406','modify','修改','reportParaAction!initModify.action','checkModify(1)',30,1,NULL,NULL,NULL,NULL,0)
,('342','422','ib_ibStatQuery_reSearch','重新查询','ShowInvoiceBalanceAction!statQuery.action',NULL,10,1,NULL,NULL,NULL,NULL,4)
,('343','422','ib_ibStatQuery_back','返回主页',NULL,'window.parent.parent.location = window.parent.parent.location;',20,1,NULL,NULL,NULL,NULL,NULL)
,('362','425','at_financeBacklog_initAdd','新增','addedTaxAction!initAdd.action',NULL,1,1,NULL,NULL,NULL,NULL,4)
,('384','426','invoiceBalance_ibFinanceQueryView_reSearch','重新查询','ShowInvoiceBalanceAction!financeQueryView.action',NULL,10,1,NULL,NULL,NULL,NULL,4)
,('385','426','invoiceBalance_ibFinanceQueryView_back','返回主页',NULL,'window.parent.parent.location = window.parent.parent.location;',10,1,NULL,NULL,NULL,NULL,NULL)
,('386','423','invoiceBalance_ibShopQueryView_reSearch','重新查询','ShowInvoiceBalanceAction!init.action?queryCode=ib_invoiceBalanceShopQueryView',NULL,10,1,NULL,NULL,NULL,NULL,4)
,('387','423','invoiceBalance_ibShopQueryView_back','返回主页',NULL,'window.parent.parent.location = window.parent.parent.location;',20,1,NULL,NULL,NULL,NULL,NULL)
,('388','425','at_financeBacklog_batchComplete','批量完成','addedTaxAction!batchComplete.action','checkDelete(1);',2,1,NULL,NULL,NULL,NULL,4)
,('4','2','deleteButton','删除','baseAction!delete.action','checkDelete(1)',20,1,NULL,NULL,NULL,NULL,1)
;
INSERT INTO test.mstb_query_button (BUTTON_ID,QUERY_ID,BUTTON_NO,BUTTON_NAME,SUB_URL,EXECUTE_JS,ORDER_NO,RECORD_STATE,CREATED_USER_ID,CREATED_TIME,UPDATED_USER_ID,UPDATED_TIME,OPEN_TYPE) VALUES 
('402','441','sa_listDetail_returnMainPage','返回主页',NULL,'window.parent.parent.location = window.parent.parent.location;',10,1,NULL,NULL,NULL,NULL,4)
,('403','441','sa_listDetail_returnQueryPage','重新查询','shopAuth/saDetailQuery.jsp',NULL,20,1,NULL,NULL,NULL,NULL,4)
,('404','441','sa_listDetail_initModify','修改','shopAuthAction!initModify.action','checkModify(1)',30,1,NULL,NULL,NULL,NULL,0)
,('405','441','sa_listDetail_initAdd','增加','shopAuthAction!initAdd.action',NULL,25,1,NULL,NULL,NULL,NULL,0)
,('406','441','sa_listDetail_enable','手动更新权限','shopAuthAction!enable.action','checkDelete(1)',40,1,NULL,NULL,NULL,NULL,1)
,('407','427','at_confirmView_reQuery','重新查询','addedTax/atConfirmViewQuery.jsp',NULL,10,1,NULL,NULL,NULL,NULL,4)
,('42','81','sysManage_module_initModify','修改','moduleAction!initModify.action','checkModify(1)',30,1,NULL,NULL,NULL,NULL,0)
,('43','81','sysManage_module_delete','删除','moduleAction!delete.action','checkDelete(1)',40,1,NULL,NULL,NULL,NULL,1)
,('44','81','sysManage_module_initAdd0','增加当前级','moduleAction!initAdd.action?moduleVo.addLevel=0',NULL,10,1,NULL,NULL,NULL,NULL,0)
,('445','504','add','增加','timeingJobAction!initAdd.action',NULL,10,1,NULL,NULL,NULL,NULL,0)
;
INSERT INTO test.mstb_query_button (BUTTON_ID,QUERY_ID,BUTTON_NO,BUTTON_NAME,SUB_URL,EXECUTE_JS,ORDER_NO,RECORD_STATE,CREATED_USER_ID,CREATED_TIME,UPDATED_USER_ID,UPDATED_TIME,OPEN_TYPE) VALUES 
('446','504','delete','删除','timeingJobAction!delete.action','checkDelete(1)',20,1,NULL,NULL,NULL,NULL,1)
,('447','504','modify','修改','timeingJobAction!initModify.action','checkModify(1)',30,1,NULL,NULL,NULL,NULL,0)
,('45','81','sysManage_module_initAdd1','增加下一级','moduleAction!initAdd.action?moduleVo.addLevel=1','checkAdd(1, 1)',20,1,NULL,NULL,NULL,NULL,0)
,('46','82','ebooking_blackList_add','增加','EbBlacklistAction!initAdd.action',NULL,10,1,NULL,NULL,NULL,NULL,0)
,('462','163','ebooking_baseParameter_modify','修改','EbBaseParameterAction!initMdf.action','checkModify(1)',20,1,NULL,NULL,NULL,NULL,0)
,('486','542','si_financeBacklog_initModify_batchComplete','批量完成','shopInvoiceAction!batchComplete.action','checkDelete(1)',10,1,NULL,NULL,NULL,NULL,1)
,('5','2','modifyButton','修改','query/query.jsp?oprt=initModify','checkModify(1)',30,1,NULL,NULL,NULL,NULL,0)
,('502','504','reset','重置','timeingJobAction!reset.action','checkDelete(1)',40,1,NULL,NULL,NULL,NULL,1)
,('542','561','ft_shopBacklog_back','返回主页',NULL,'window.parent.parent.location = window.parent.parent.location;',10,1,NULL,NULL,NULL,NULL,NULL)
,('543','562','ft_financeBacklog_back','返回主页',NULL,'window.parent.parent.location = window.parent.parent.location;',10,1,NULL,NULL,NULL,NULL,NULL)
;
INSERT INTO test.mstb_query_button (BUTTON_ID,QUERY_ID,BUTTON_NO,BUTTON_NAME,SUB_URL,EXECUTE_JS,ORDER_NO,RECORD_STATE,CREATED_USER_ID,CREATED_TIME,UPDATED_USER_ID,UPDATED_TIME,OPEN_TYPE) VALUES 
('544','563','ft_statQuery_back','返回主页',NULL,'window.parent.parent.location = window.parent.parent.location;',30,1,NULL,NULL,NULL,NULL,NULL)
,('545','563','ft_statQuery_reSearch','重新查询','showFinanceTaxAction!statQuery.action',NULL,20,1,NULL,NULL,NULL,NULL,4)
,('546','564','ft_shopQueryView_reSearch','重新查询','showFinanceTaxAction!init.action?queryCode=ft_shopQueryView',NULL,10,1,NULL,NULL,NULL,NULL,4)
,('547','564','ft_shopQueryView_back','返回主页','showFinanceTaxAction!init.action?queryCode=ft_shopQueryView',NULL,20,1,NULL,NULL,NULL,NULL,4)
,('548','565','ft_financeQueryView_back','返回主页',NULL,'window.parent.parent.location = window.parent.parent.location;',30,1,NULL,NULL,NULL,NULL,NULL)
,('549','565','ft_financeQueryView_reSearch','重新查询','showFinanceTaxAction!financeQueryView.action',NULL,20,1,NULL,NULL,NULL,NULL,4)
,('550','566','ft_joinMeetingQuery_back','返回主页',NULL,'window.parent.parent.location = window.parent.parent.location;',10,1,NULL,NULL,NULL,NULL,NULL)
,('551','566','ft_joinMeetingQuery_reSearch','重新查询','showFinanceTaxAction!joinMeetingQuery.action',NULL,20,1,NULL,NULL,NULL,NULL,4)
,('552','424','ib_financeBacklog_batchDelete','删除','InvoiceBalanceAction!batchDelete.action','checkDelete(1)',10,1,NULL,NULL,NULL,NULL,1)
,('562','581','ib_bankList_add','新增','BankAction!initAdd.action',NULL,10,1,NULL,NULL,NULL,NULL,0)
;
INSERT INTO test.mstb_query_button (BUTTON_ID,QUERY_ID,BUTTON_NO,BUTTON_NAME,SUB_URL,EXECUTE_JS,ORDER_NO,RECORD_STATE,CREATED_USER_ID,CREATED_TIME,UPDATED_USER_ID,UPDATED_TIME,OPEN_TYPE) VALUES 
('563','581','ib_bankList_modify','修改','BankAction!initModify.action','checkModify(1)',20,1,NULL,NULL,NULL,NULL,0)
,('564','581','ib_bankList_del','删除','BankAction!delete.action','checkDelete(1)',30,1,NULL,NULL,NULL,NULL,1)
,('565','562','ft_financeBacklog_batchDelete','删除','financeTaxAction!batchDelete.action','checkDelete(1)',1,1,NULL,NULL,NULL,NULL,1)
,('568','428','at_InfoView_reQuery','重新查询','addedTax/atInfoViewQuery.jsp',NULL,10,1,NULL,NULL,NULL,NULL,4)
,('569','428','at_InfoView_homepage','返回主页',NULL,'window.parent.parent.location = window.parent.parent.location; ',20,1,NULL,NULL,NULL,NULL,4)
,('571','601','si_listStatistics_returnQueryPage','重新查询','showShopInvoiceAction!init.action?queryCode=si_listStatistics',NULL,20,1,NULL,NULL,NULL,NULL,4)
,('572','427','at_InfoView_homepage','返回主页',NULL,'window.parent.parent.location = window.parent.parent.location;',20,1,NULL,NULL,NULL,NULL,4)
,('575','170','rf_commQuery_reQuery','重新查询','showBankRefundAction.action?queryCode=bank_comm_query',NULL,12,1,NULL,NULL,NULL,NULL,4)
,('582','621','si_listDetailShop_reQuery','重新查询','showShopInvoiceAction!init.action?queryCode=si_listDetailShop',NULL,10,1,NULL,NULL,NULL,NULL,4)
,('584','622','si_listDetail_reQuery','重新查询','showShopInvoiceAction!init.action?queryCode=si_listDetail',NULL,10,1,NULL,NULL,NULL,NULL,4)
;
INSERT INTO test.mstb_query_button (BUTTON_ID,QUERY_ID,BUTTON_NO,BUTTON_NAME,SUB_URL,EXECUTE_JS,ORDER_NO,RECORD_STATE,CREATED_USER_ID,CREATED_TIME,UPDATED_USER_ID,UPDATED_TIME,OPEN_TYPE) VALUES 
('602','262','cr_commQuery_requery','重新查询','checkReturn/crCommonQuery.jsp',NULL,3,1,NULL,NULL,NULL,NULL,4)
,('624','425','at_financeBacklog_homepage','返回主页',NULL,'window.parent.parent.location = window.parent.parent.location;',12,1,NULL,NULL,NULL,NULL,NULL)
,('625','403','at_shopBacklog_homepage','返回主页',NULL,'window.parent.parent.location = window.parent.parent.location;',10,1,NULL,NULL,NULL,NULL,NULL)
,('642','701','smt_bankList_add','新增','BankAction!initAdd.action',NULL,10,1,NULL,NULL,NULL,NULL,0)
,('643','701','smt_bankList_modify','修改','BankAction!initModify.action','checkModify(1)',20,1,NULL,NULL,NULL,NULL,0)
,('644','701','smt_bankList_del','删除','BankAction!delete.action','checkDelete(1)',30,1,NULL,NULL,NULL,NULL,1)
,('65','103','add','增加','roleUserAction!initAdd.action',NULL,10,1,NULL,NULL,NULL,NULL,0)
,('66','103','delete','删除','roleUserAction!delete.action','checkDelete(1)',20,1,NULL,NULL,NULL,NULL,1)
,('67','103','return','返回',NULL,'window.close()',30,1,NULL,NULL,NULL,NULL,NULL)
,('682','2','testButton','测试',NULL,'checkModify(1)',40,1,NULL,NULL,NULL,NULL,1)
;
INSERT INTO test.mstb_query_button (BUTTON_ID,QUERY_ID,BUTTON_NO,BUTTON_NAME,SUB_URL,EXECUTE_JS,ORDER_NO,RECORD_STATE,CREATED_USER_ID,CREATED_TIME,UPDATED_USER_ID,UPDATED_TIME,OPEN_TYPE) VALUES 
('702','761','TestButton','测试','pages/praise_edition/demand/importFile.html',NULL,10,1,NULL,NULL,NULL,NULL,0)
,('722','781','CFG_PIN_ADD','增加','pinAction!initAdd.action',NULL,10,1,NULL,NULL,NULL,NULL,0)
,('723','781','CFG_PIN_MODIFY','修改','pinAction!initModify.action','checkModify(1)',20,1,NULL,NULL,NULL,NULL,0)
,('724','782','PIN_RELEVANCE_ADD','绑定职级关系','showAction.action?queryCode=CFG_PIN_LIST',NULL,10,1,NULL,NULL,NULL,NULL,0)
,('725','782','PIN_RELEVANCE_DELETE','删除职级关联','pinRelevanceAction!delete.action','checkDelete(1)',20,1,NULL,NULL,NULL,NULL,1)
,('742','802','PRAISE_TYPE_PROJECT_ADD','增加','praiseTypeAction!initAdd.action',NULL,10,1,NULL,NULL,NULL,NULL,0)
,('743','802','PRAISE_TYPE_PROJECT_MODIFY','修改','praiseTypeAction!initModify.action','checkModify(1)',20,1,NULL,NULL,NULL,NULL,0)
,('744','803','CFG_PRAISE_CONTENT_ADD','增加','praiseContentAction!initAdd.action',NULL,10,1,NULL,NULL,NULL,NULL,0)
,('745','803','CFG_PRAISE_CONTENT_MODIFY','修改','praiseContentAction!initModify.action','checkModify(1)',20,1,NULL,NULL,NULL,NULL,0)
,('746','804','CFG_WELFARE_ADD','增加','welfareAction!initAdd.action',NULL,10,1,NULL,NULL,NULL,NULL,0)
;
INSERT INTO test.mstb_query_button (BUTTON_ID,QUERY_ID,BUTTON_NO,BUTTON_NAME,SUB_URL,EXECUTE_JS,ORDER_NO,RECORD_STATE,CREATED_USER_ID,CREATED_TIME,UPDATED_USER_ID,UPDATED_TIME,OPEN_TYPE) VALUES 
('747','804','CFG_WELFARE_MODIFY','修改','welfareAction!initModify.action','checkModify(1)',20,1,NULL,NULL,NULL,NULL,0)
,('748','805','GDS_GOODS_COMPONENT_ADD','增加','goodsAction!initAddComponent.action',NULL,10,1,NULL,NULL,NULL,NULL,0)
,('749','805','GDS_GOODS_COMPONENT_MODIFY','修改','goodsAction!initModifyComponent.action','checkModify(1)',20,1,NULL,NULL,NULL,NULL,0)
,('750','806','GDS_GOODS_ADD','增加','goodsAction!initAdd.action',NULL,10,1,NULL,NULL,NULL,NULL,0)
,('751','806','GDS_GOODS_MODIFY','修改','goodsAction!initModify.action','checkModify(1)',20,1,NULL,NULL,NULL,NULL,0)
,('752','807','GDS_GOODS_BINDIND_ADD','绑定组件关系','goodsAction!initRelation.action',NULL,10,1,NULL,NULL,NULL,NULL,0)
,('753','807','GDS_GOODS_BINDIND_DELETE','删除组件关系','goodsAction!deleteRelation.action','checkDelete(1)',20,1,NULL,NULL,NULL,NULL,1)
,('762','821','GDS_WAREHOUSE_IN_ADD','入仓','initIn.action','checkModify(1)',10,1,NULL,NULL,NULL,NULL,0)
,('763','821','GDS_WAREHOUSE_IN_BACK','退回','initOut.action','checkModify(1)',20,1,NULL,NULL,NULL,NULL,0)
,('764','823','GDS_WAREHOUSE_ASSIGN_ADD','分配','initAssign.action','checkModify(1)',10,1,NULL,NULL,NULL,NULL,0)
;
INSERT INTO test.mstb_query_button (BUTTON_ID,QUERY_ID,BUTTON_NO,BUTTON_NAME,SUB_URL,EXECUTE_JS,ORDER_NO,RECORD_STATE,CREATED_USER_ID,CREATED_TIME,UPDATED_USER_ID,UPDATED_TIME,OPEN_TYPE) VALUES 
('765','823','GDS_WAREHOUSE_ASSIGN_BACK','回收','initUnAssign.action','checkModify(1)',20,1,NULL,NULL,NULL,NULL,0)
,('766','824','GDS_WAREHOUSE_LOSS_LOSS','物品损耗','initLoss.action','checkModify(1)',10,1,NULL,NULL,NULL,NULL,0)
,('767','824','GDS_WAREHOUSE_LOSS_BACK','撤回损耗','initUnLoss.action','checkModify(1)',20,1,NULL,NULL,NULL,NULL,0)
,('782','822','PRAISE_LIST_STAR_IMPORT','导入认承名单','initImportQualify.action?listType=S',NULL,10,1,NULL,NULL,NULL,NULL,0)
,('783','822','PRAISE_LIST_STAR_MODIFY','修改','initModifyPraiseList.action','checkDelete(1)',30,1,NULL,NULL,NULL,NULL,0)
,('784','822','PRAISE_LIST_STAR_CONFIRM','确认表扬名单',NULL,'$confirm(''S'')',40,1,NULL,NULL,NULL,NULL,NULL)
,('785','822','PRAISE_LIST_STAR_GENERATE','生成表扬名单','initGeneratePraiseList.action?listType=S',NULL,20,1,NULL,NULL,NULL,NULL,0)
,('786','842','PRAISE_LIST_POST_IMPORT','导入认承名单','initImportQualify.action?listType=A',NULL,10,1,NULL,NULL,NULL,NULL,0)
,('787','842','PRAISE_LIST_POST_GENERATE','生成表扬名单','initGeneratePraiseList.action?listType=A',NULL,20,1,NULL,NULL,NULL,NULL,0)
,('788','842','PRAISE_LIST_POST_MODIFY','修改','initModifyPraiseList.action','checkDelete(1)',30,1,NULL,NULL,NULL,NULL,0)
;
INSERT INTO test.mstb_query_button (BUTTON_ID,QUERY_ID,BUTTON_NO,BUTTON_NAME,SUB_URL,EXECUTE_JS,ORDER_NO,RECORD_STATE,CREATED_USER_ID,CREATED_TIME,UPDATED_USER_ID,UPDATED_TIME,OPEN_TYPE) VALUES 
('789','842','PRAISE_LIST_POST_CONFIRM','确认表扬名单',NULL,'$confirm(''A'')',40,1,NULL,NULL,NULL,NULL,0)
,('802','841','GDS_WAREHOUSE_OUT_MODIFY','修改(勾选记录)','initWareHouseOutModify.action','checkDelete(1)',10,1,NULL,NULL,NULL,NULL,0)
,('803','841','GDS_WAREHOUSE_OUT_MODIFYALL','修改(全选记录)','initWareHouseOutModifyAll.action?query_code=GDS_WAREHOUSE_OUT',NULL,20,1,NULL,NULL,NULL,NULL,0)
,('804','841','GDS_WAREHOUSE_OUT_IMPORT','导入安利卡号查询','distImportAction!initImportExcel.action?type=4',NULL,30,1,NULL,NULL,NULL,NULL,0)
,('805','862','DST_PICTURE_MANAGE_ADD','增加','pictrueManageAction!initAdd.action',NULL,10,1,NULL,NULL,NULL,NULL,0)
,('806','862','DST_PICTURE_MANAGE_MODIFY','修改','pictrueManageAction!initModify.action','checkModify(1)',20,1,NULL,NULL,NULL,NULL,0)
,('807','862','DST_PICTURE_MANAGE_DELETE','删除','pictrueManageAction!delete.action','checkDelete(1)',30,1,NULL,NULL,NULL,NULL,1)
,('808','862','DST_PICTURE_MANAGE_IMPORT_DATA','导入数据','pictrueManageAction!initImport.action',NULL,40,1,NULL,NULL,NULL,NULL,0)
,('809','862','T_PICTURE_MANAGE_IMPORT','导入安利卡号查询','distImportAction!initImportExcel.action?type=5',NULL,50,1,NULL,NULL,NULL,NULL,0)
,('82','141','sysManage_application_initAdd','增加','applicationAction!initAdd.action',NULL,10,1,NULL,NULL,NULL,NULL,0)
;
INSERT INTO test.mstb_query_button (BUTTON_ID,QUERY_ID,BUTTON_NO,BUTTON_NAME,SUB_URL,EXECUTE_JS,ORDER_NO,RECORD_STATE,CREATED_USER_ID,CREATED_TIME,UPDATED_USER_ID,UPDATED_TIME,OPEN_TYPE) VALUES 
('8201057','8201313','reginfo_delete_btn','刪除','regInfoDetailAction!delete.action','checkDelete(1)',10,1,NULL,NULL,NULL,NULL,1)
,('822','884','MEETING_SEARCH_MODIFY','修改（勾选记录）','meetingAction!initModify.action','checkDelete(1)',10,1,NULL,NULL,NULL,NULL,0)
,('823','884','MEETING_SEARCH_MODIFY_ALL','修改（全部记录）','meetingAction!initModifyAll.action?queryCode=MEETING_SEARCH',NULL,20,1,NULL,NULL,NULL,NULL,0)
,('824','884','MEETING_SEARCH_IMPORT_DIST_NUMBER','导入安利卡号查询','distImportAction!initImportExcel.action?type=1',NULL,30,1,NULL,NULL,NULL,NULL,0)
,('825','887','PRA_PRAISE_LIST_INIT_DRAFT_DELETE','取消','praiseListAction!backInit.action','cancel()',10,1,NULL,NULL,NULL,NULL,4)
,('826','887','PRA_PRAISE_LIST_INIT_DRAFT_MODIFY','修改(勾选记录)','praiseListAction!initModifyFirstDraft.action','checkDelete(1)',20,1,NULL,NULL,NULL,NULL,0)
,('827','887','PRA_PRAISE_LIST_INIT_DRAFT_ADD','生成表扬榜终稿','praiseListAction!finalDraftInput.action',NULL,30,1,NULL,NULL,NULL,NULL,0)
,('828','888','PRA_PRAISE_LIST_FINAL_DRAFT_BACK','返回上一步','praiseListAction!backFirstDraft.action',NULL,10,1,NULL,NULL,NULL,NULL,4)
,('829','888','PRA_PRAISE_LIST_FINAL_DRAFT_ADD','确定表扬榜终稿',NULL,'confirmFinalDraft(''/amway-praise/praiseListAction!confirmFinalDraft.action'')',20,1,NULL,NULL,NULL,NULL,1)
,('83','141','sysManage_application_delete','删除','applicationAction!delete.action','checkDelete(1)',20,1,NULL,NULL,NULL,NULL,1)
;
INSERT INTO test.mstb_query_button (BUTTON_ID,QUERY_ID,BUTTON_NO,BUTTON_NAME,SUB_URL,EXECUTE_JS,ORDER_NO,RECORD_STATE,CREATED_USER_ID,CREATED_TIME,UPDATED_USER_ID,UPDATED_TIME,OPEN_TYPE) VALUES 
('830','891','WELFARE_SEARCH_MODIFY','修改（勾选记录）','awdWelfareAction!initModify.action','checkDelete(1)',10,1,NULL,NULL,NULL,NULL,0)
,('831','891','WELFARE_SEARCH_MODIFY_ALL','修改（全部记录）','awdWelfareAction!initModifyAll.action?queryCode=WELFARE_SEARCH',NULL,20,1,NULL,NULL,NULL,NULL,0)
,('832','891','WELFARE_SEARCH_IMPORT_DIST_NUMBER','导入安利卡号查询','distImportAction!initImportExcel.action?type=3',NULL,30,1,NULL,NULL,NULL,NULL,0)
,('833','890','PRA_GRADING_IMPORT_ADD','增加','gradingAction!initAdd.action',NULL,10,1,NULL,NULL,NULL,NULL,0)
,('834','890','PRA_GRADING_IMPORT_MODIFY','修改','gradingAction!initModify.action','checkModify(1)',20,1,NULL,NULL,NULL,NULL,0)
,('835','890','PRA_GRADING_IMPORT_DATA','导入定级名单','gradingAction!initImportExcel.action',NULL,30,1,NULL,NULL,NULL,NULL,0)
,('836','890','PRA_GRADING_IMPORT_CONFIRM','确定定级名单',NULL,'ajaxSubmitMessage2(''ec'',''/amway-praise/gradingAction!confirmGrading.action'',false,confirmGrading,false)',40,1,NULL,NULL,NULL,NULL,1)
,('84','141','sysManage_application_initModify','修改','applicationAction!initModify.action','checkModify(1)',30,1,NULL,NULL,NULL,NULL,0)
,('842','883','NOMINATE_SEARCH_MODIFY','修改（勾选记录）','nominateAction!initModify.action','checkDelete(1)',10,1,NULL,NULL,NULL,NULL,0)
,('843','883','NOMINATE_SEARCH_MODIFY_ALL','修改（全部记录）','nominateAction!initModifyAll.action?queryCode=NOMINATE_SEARCH',NULL,20,1,NULL,NULL,NULL,NULL,0)
;
INSERT INTO test.mstb_query_button (BUTTON_ID,QUERY_ID,BUTTON_NO,BUTTON_NAME,SUB_URL,EXECUTE_JS,ORDER_NO,RECORD_STATE,CREATED_USER_ID,CREATED_TIME,UPDATED_USER_ID,UPDATED_TIME,OPEN_TYPE) VALUES 
('844','883','NOMINATE_SEARCH_IMPORT_DIST_NUMBER','导入安利卡号查询','distImportAction!initImportExcel.action?type=0',NULL,30,1,NULL,NULL,NULL,NULL,0)
,('845','889','OTHER_SEARCH_ADD','增加','otherAction!initAdd.action',NULL,10,1,NULL,NULL,NULL,NULL,0)
,('846','889','OTHER_SEARCH_MODIFY','修改','otherAction!initModify.action','checkModify(1)',20,1,NULL,NULL,NULL,NULL,0)
,('847','889','OTHER_SEARCH_DELETE','删除','otherAction!delete.action','checkDelete(1)',30,1,NULL,NULL,NULL,NULL,1)
,('848','889','OTHER_SEARCH_IMPORT_EXECUTE_RESULT','导入执行结果','otherAction!uploadView.action',NULL,40,1,NULL,NULL,NULL,NULL,0)
,('849','889','OTHER_SEARCH_IMPORT_DIST_NUMBER','导入安利卡号查询','distImportAction!initImportExcel.action?type=2',NULL,50,1,NULL,NULL,NULL,NULL,0)
,('862','864','DST_PUBLISH_DESIRE_IMPORT','导入安利卡号查询','distImportAction!initImportExcel.action?type=6',NULL,10,1,NULL,NULL,NULL,NULL,0)
,('882','921','PRA_PRAISE_INIT_CREATE','生成表扬榜初稿','praiseListAction!firstDraftInput.action',NULL,10,1,NULL,NULL,NULL,NULL,0)
,('90','143','sysManage_role_initAdd','增加','roleAction!initAdd.action',NULL,10,1,NULL,NULL,NULL,NULL,0)
,('902','890','PRA_GRADING_IMPORT_DELETE','删除','gradingAction!delete.action','checkDelete(1)',25,1,NULL,NULL,NULL,NULL,1)
;
INSERT INTO test.mstb_query_button (BUTTON_ID,QUERY_ID,BUTTON_NO,BUTTON_NAME,SUB_URL,EXECUTE_JS,ORDER_NO,RECORD_STATE,CREATED_USER_ID,CREATED_TIME,UPDATED_USER_ID,UPDATED_TIME,OPEN_TYPE) VALUES 
('91','143','sysManage_role_delete','删除','roleAction!delete.action','checkDelete(1)',20,1,NULL,NULL,NULL,NULL,1)
,('92','143','sysManage_role_initModify','修改','roleAction!initModify.action','checkModify(1)',30,1,NULL,NULL,NULL,NULL,0)
,('922','892','PRA_GRADING_DELETE','删除(勾选记录)','gradingAction!deleteGrading.action','checkDelete(1)',20,1,NULL,NULL,NULL,NULL,1)
,('93','144','ebooking_meetingRoom_add','新增','EbMeetingRoomAction!initAdd.action',NULL,10,1,NULL,NULL,NULL,NULL,0)
,('94','144','ebooking_meetingRoom_del','删除','EbMeetingRoomAction!delete.action','checkDelete(1)',20,1,NULL,NULL,NULL,NULL,1)
,('942','941','CFG_PIN_LIST_BING','绑定','pinRelevanceAction!add.action','checkDelete(1)',10,1,NULL,NULL,NULL,NULL,1)
,('95','144','ebooking_meetingRoom_modify','修改','EbMeetingRoomAction!initMdf.action','checkModify(1)',30,1,NULL,NULL,NULL,NULL,0)
,('982','863','deletePraiseList','删除(勾选记录)',NULL,'$delete()',10,1,NULL,NULL,NULL,NULL,4)
,('99201058','99201347','cad_draftList_initAdd','新建','cashDiaryAcctAction!initAdd.action',NULL,10,1,NULL,NULL,NULL,NULL,0)
;