INSERT INTO test.mstb_query_index (QUERY_ID,QUERY_CODE,QUERY_NAME,APPLICATION_ID,DS_JNDI,IS_COL_HEA_FIL,EXTERNAL_JS,IS_DEFAULT_QRY,GLOBAL_WHERE,REMARE,USE_STATE,RECORD_STATE,CREATED_USER_ID,CREATED_TIME,UPDATED_USER_ID,UPDATED_TIME,IS_REFRESH) VALUES 
('100001','sms_log_query','sms_log_query','100001','jdbcamway',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('100003','menu1','menu1','100005','jdbcamway',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('100005','kgem_root_km_klist','知识列表','100007','jdbcamway',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('100006','commonquery_ad','通用查询','1','jdbcamway',1,'http://localhost:8080/query/common/js/test.js',0,NULL,'r24d',1,1,NULL,NULL,NULL,NULL,1)
,('100007','mysqlquery','mysqlquery','100005','jdbcmysql',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('100012','appquery_ad','应用设置维护','1','jdbcamway',1,NULL,0,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('100014','modulequery_ad','功能信息维护','1','jdbcamway',1,NULL,0,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('100018','rolequery_ad','角色信息维护','1','jdbcamway',1,NULL,0,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('100020','roleuserquery_ad','角色分配用户','1','jdbcamway',1,NULL,0,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('100022','extappquery_ad','扩展应用配置','1','jdbcamway',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
;
INSERT INTO test.mstb_query_index (QUERY_ID,QUERY_CODE,QUERY_NAME,APPLICATION_ID,DS_JNDI,IS_COL_HEA_FIL,EXTERNAL_JS,IS_DEFAULT_QRY,GLOBAL_WHERE,REMARE,USE_STATE,RECORD_STATE,CREATED_USER_ID,CREATED_TIME,UPDATED_USER_ID,UPDATED_TIME,IS_REFRESH) VALUES 
('100024','mailtemplatequery_ad','邮件模板配置','1','jdbcamway',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('100026','shortmessagequery_ad','短信模板配置','1','jdbcamway',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('100028','bdsquery_ad','基础数据服务','1','jdbcamway',1,NULL,0,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('100030','oplogquery_ad','操作日志','1','jdbcamway',1,NULL,0,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('100032','timetaskquery_ad','定时任务配置','1','jdbcamway',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('100034','timereportquery_ad','定时报表设置','1','jdbcamway',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('1001','smt_cancel_list','查看所有被取消表单','301','jdbcamway',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('1002','pos_sum','POS付款汇总表','200502','jdbcamwayApp',1,NULL,0,NULL,NULL,1,1,NULL,NULL,NULL,NULL,0)
,('1003','pos_detail','POS付款明细表','200502','jdbcamwayApp',1,NULL,0,NULL,NULL,1,1,NULL,NULL,NULL,NULL,0)
,('101','sysManage_roleUser','角色分配用户','1','jdbcamway',1,NULL,0,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
;
INSERT INTO test.mstb_query_index (QUERY_ID,QUERY_CODE,QUERY_NAME,APPLICATION_ID,DS_JNDI,IS_COL_HEA_FIL,EXTERNAL_JS,IS_DEFAULT_QRY,GLOBAL_WHERE,REMARE,USE_STATE,RECORD_STATE,CREATED_USER_ID,CREATED_TIME,UPDATED_USER_ID,UPDATED_TIME,IS_REFRESH) VALUES 
('1021','si_cancel_list','查看所有被取消表单','241','jdbcamway',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('103','05','分配单个用户','1','jdbcamway',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('1041','at_cancel_list','查看所有被取消表单','201','jdbcamway',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('1042','ib_cancel_list','查看所有被取消表单','203','jdbcamway',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('1061','checkReturn_cancel_list','查看所有被取消申请','101','jdbcamway',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('1081','FC_Contact_Record','Contact Report','542','jdbcamway',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('1082','FC_List','FC List','542','jdbcamway',0,NULL,1,'FC_LIST.Status =1',NULL,1,1,NULL,NULL,NULL,NULL,0)
,('1102','mt_cancel_list','查看所有取消表单','121','jdbcamway',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('1121','FC_Contact_Record_ALL','Contact Report(约见情况)','542','jdbcamway',0,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('1122','FC_Province','省份报表','542','jdbcamway',0,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,0)
;
INSERT INTO test.mstb_query_index (QUERY_ID,QUERY_CODE,QUERY_NAME,APPLICATION_ID,DS_JNDI,IS_COL_HEA_FIL,EXTERNAL_JS,IS_DEFAULT_QRY,GLOBAL_WHERE,REMARE,USE_STATE,RECORD_STATE,CREATED_USER_ID,CREATED_TIME,UPDATED_USER_ID,UPDATED_TIME,IS_REFRESH) VALUES 
('1124','checkReturn_comm_query_tp','自定义查询','101','jdbcamway',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('1125','bank_comm_query_tp','自定义查询','2','jdbcamway',1,'/refund/include/js/bankRefund.js',1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('1141','ft_cancel_list','查看历史取消表单','261','jdbcamway',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('1142','bankRefund_cancel_list','查看历史取消表单','2','jdbcamway',1,'/refund/include/js/bankRefund.js',1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('1321','cpc_search','CPC Report','661','jdbcamwayAmanet',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,0)
,('1341','mi_print_item_bak','邮寄文档菜单—恳请不要删除','561','jdbcamway',1,NULL,0,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('1401','mi_print_item_bak130523','邮寄清单','561','jdbcamway',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('141','afw_application','应用设置维护','1','jdbcamway',1,'',1,'','',1,1,NULL,NULL,NULL,NULL,1)
,('1429805441228','test11','test11','100007','jdbcamway',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('143','afw_role','角色信息维护','1','jdbcamway',1,NULL,0,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
;
INSERT INTO test.mstb_query_index (QUERY_ID,QUERY_CODE,QUERY_NAME,APPLICATION_ID,DS_JNDI,IS_COL_HEA_FIL,EXTERNAL_JS,IS_DEFAULT_QRY,GLOBAL_WHERE,REMARE,USE_STATE,RECORD_STATE,CREATED_USER_ID,CREATED_TIME,UPDATED_USER_ID,UPDATED_TIME,IS_REFRESH) VALUES 
('1430210161923','myquery','myquery','100007','jdbcamway',1,'',1,'','',1,1,NULL,NULL,NULL,NULL,1)
,('144','ebooking_meetingRoom','会议室管理','21','jdbcamway',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('1481','bank_custom_query','自定义查询','2','jdbcamway',1,'/refund/include/js/bankRefund.js',1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('161','bankRefund_shop','待办流程','2','jdbcamway',1,NULL,1,'(${formState} or ${formState2})',NULL,1,1,NULL,NULL,NULL,NULL,1)
,('162','ebooking_myMeeting','我的会议','21','jdbcamway',1,NULL,1,'(${userProfileId} or ${empNumber})',NULL,1,1,NULL,NULL,NULL,NULL,1)
,('163','ebooking.ebBaseParameter','系统参数管理','21','jdbcamway',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('164','ebooking_location','会议室位置管理','21','jdbcamway',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('165','ebEquipment','会议室设施管理','21','jdbcamway',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('166','ebooking_bookingReport','统计报表','21','jdbcamway',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('167','sysManage_appPlus','扩展应用配置','1','jdbcamway',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
;
INSERT INTO test.mstb_query_index (QUERY_ID,QUERY_CODE,QUERY_NAME,APPLICATION_ID,DS_JNDI,IS_COL_HEA_FIL,EXTERNAL_JS,IS_DEFAULT_QRY,GLOBAL_WHERE,REMARE,USE_STATE,RECORD_STATE,CREATED_USER_ID,CREATED_TIME,UPDATED_USER_ID,UPDATED_TIME,IS_REFRESH) VALUES 
('168','sysManage_blacklist','应用黑名单设置','1','jdbcamway',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('169','bankRefund_finance','待办流程','2','jdbcamway',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('170','bank_comm_query','自定义查询','2','jdbcamway',1,'/refund/include/js/bankRefund.js',1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('1703','mi_print_item_bak130625','邮寄清单','561','jdbcamway',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('181','sysManage_emailTemplate','邮件模板配置','1','jdbcamway',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('1821','mi_print_item','邮寄清单','561','jdbcamway',1,'/mailInventory/include/js/printInfo.js',1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,0)
,('1923','mi_print_item_bak130709','邮寄清单_请不要删除','561','jdbcamway',1,'/mailInventory/include/js/printInfo.js',1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,0)
,('2','01','通用查询','1','jdbcamway',1,'http://localhost:8080/query/common/js/test.js',0,NULL,'r24d',1,1,NULL,NULL,NULL,NULL,1)
,('2001','mi_print_item_bakddd','邮寄清单','561','jdbcamway',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('200761','br_dic_shopMgt','店铺列表','200502','jdbcamwayApp',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
;
INSERT INTO test.mstb_query_index (QUERY_ID,QUERY_CODE,QUERY_NAME,APPLICATION_ID,DS_JNDI,IS_COL_HEA_FIL,EXTERNAL_JS,IS_DEFAULT_QRY,GLOBAL_WHERE,REMARE,USE_STATE,RECORD_STATE,CREATED_USER_ID,CREATED_TIME,UPDATED_USER_ID,UPDATED_TIME,IS_REFRESH) VALUES 
('200781','br_dic_rateMgt','费率列表','200502','jdbcamwayApp',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('200801','br_base_job','工作项列表','200502','jdbcamwayApp',0,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('200802','br_base_trace','业务更新跟踪列表','200502','jdbcamwayApp',0,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('200803','br_base_job_detail','明细差异对账工作项','200502','jdbcamwayApp',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('200821','br_report_banksum','网银汇总列表 ','200502','jdbcamwayApp',1,NULL,0,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('200822','br_report_poscenter','银行Center列表','200502','jdbcamwayApp',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('200841','br_report_recondetail_tp1m1','交易明细差异主表','200502','jdbcamwayApp',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('200842','br_report_recondetail_tp2m1','交易明细差异主表','200502','jdbcamwayApp',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('200843','br_report_recondetail_tp3m1','交易明细差异主表','200502','jdbcamwayApp',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('200844','br_report_recondetail_tp1ad','交易明细差异附表','200502','jdbcamwayApp',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
;
INSERT INTO test.mstb_query_index (QUERY_ID,QUERY_CODE,QUERY_NAME,APPLICATION_ID,DS_JNDI,IS_COL_HEA_FIL,EXTERNAL_JS,IS_DEFAULT_QRY,GLOBAL_WHERE,REMARE,USE_STATE,RECORD_STATE,CREATED_USER_ID,CREATED_TIME,UPDATED_USER_ID,UPDATED_TIME,IS_REFRESH) VALUES 
('200863','br_report_recondetail_tp2ad','交易明细差异附表','200502','jdbcamwayApp',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('200865','br_report_recondetail_tp3ad','交易明细差异附表','200502','jdbcamwayApp',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('200867','br_report_recondetail','明细差异报表查询','200502','jdbcamwayApp',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('200881','br_report_recondetail1','明细差异报表（中行）查询','200502','jdbcamwayApp',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('200901','br_report_recondetail2','明细差异报表（直联代扣）查询','200502','jdbcamwayApp',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('200902','br_report_recondetail3','明细差异报表（支付宝）查询','200502','jdbcamwayApp',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('200921','br_report_recondsum','总差异报表','200502','jdbcamwayApp',0,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('200941','br_sumreport_1','银行Center匹配表','200502','jdbcamwayApp',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('200942','br_sumreport_2','网银对账单匹配表','200502','jdbcamwayApp',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('200961','br_sumreport_3','银行Center不匹配','200502','jdbcamwayApp',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
;
INSERT INTO test.mstb_query_index (QUERY_ID,QUERY_CODE,QUERY_NAME,APPLICATION_ID,DS_JNDI,IS_COL_HEA_FIL,EXTERNAL_JS,IS_DEFAULT_QRY,GLOBAL_WHERE,REMARE,USE_STATE,RECORD_STATE,CREATED_USER_ID,CREATED_TIME,UPDATED_USER_ID,UPDATED_TIME,IS_REFRESH) VALUES 
('200962','br_sumreport_4','网银对账单不匹配','200502','jdbcamwayApp',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('200983','candice_test','测试','200502','jdbcamwayApp',1,NULL,1,NULL,NULL,0,1,NULL,NULL,NULL,NULL,1)
,('201','bds_schemaInfor','基础数据服务','1','jdbcamway',1,NULL,0,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('201001','br_dic_bankMgt','银行列表','200502','jdbcamwayApp',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('201296','fr_finance_report_dept','部门财务报表','200520','jdbcamway',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('201297','fr_finance_report_shop','店铺财务报表','200520','jdbcamway',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('201298','fr_report_upload_log','报表上传日志','200520','jdbcamway',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('201299','fr_finance_report_all','所有财务报表','200520','jdbcamway',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('201300','fr_finance_report_area','区域财务报表','200520','jdbcamway',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('201301','fr_report_code','报表代码维护','200520','jdbcamway',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
;
INSERT INTO test.mstb_query_index (QUERY_ID,QUERY_CODE,QUERY_NAME,APPLICATION_ID,DS_JNDI,IS_COL_HEA_FIL,EXTERNAL_JS,IS_DEFAULT_QRY,GLOBAL_WHERE,REMARE,USE_STATE,RECORD_STATE,CREATED_USER_ID,CREATED_TIME,UPDATED_USER_ID,UPDATED_TIME,IS_REFRESH) VALUES 
('201302','fr_finance_report_area_for_finance','区域财务报表(管理员)','200520','jdbcamway',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('201303','fr_finance_report_dept_for_finance','部门财务报表(管理员)','200520','jdbcamway',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('201304','fr_finance_report_all_for_finance','所有财务报表(管理员)','200520','jdbcamway',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('201305','fr_finance_report_shop_for_finance','店铺财务报表(管理员)','200520','jdbcamway',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('201306','fr_report_type','报表类型维护','200520','jdbcamway',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('201307','fr_report_code_temp','临时代码表','200520','jdbcamway',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('201309','fr_report_upload_log_admin','报表上传日志(管理员）','200520','jdbcamway',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('201310','FC_SELECT_USER','用户信息维护','542','jdbcamway',0,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('201311','FC_ALLOT_USER','分配单个用户','542','jdbcamway',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('201312','Rules_Issue','Rules Issue(守则情况)','542','jdbcamway',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
;
INSERT INTO test.mstb_query_index (QUERY_ID,QUERY_CODE,QUERY_NAME,APPLICATION_ID,DS_JNDI,IS_COL_HEA_FIL,EXTERNAL_JS,IS_DEFAULT_QRY,GLOBAL_WHERE,REMARE,USE_STATE,RECORD_STATE,CREATED_USER_ID,CREATED_TIME,UPDATED_USER_ID,UPDATED_TIME,IS_REFRESH) VALUES 
('201313','Health_Family_Edit','Health & Family (健康状况及家庭)','542','jdbcamway',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('201314','Other_Activity_Edit','Other Activity  Edit 其他慈善机构情况','542','jdbcamway',1,NULL,1,NULL,'编辑列表',0,1,NULL,NULL,NULL,NULL,1)
,('201315','Global_Recogniton','Global Recogniton 美国总部表扬情况','542','jdbcamway',1,NULL,1,NULL,NULL,0,1,NULL,NULL,NULL,NULL,1)
,('201316','Rules_Issue_Edit','Rules Issue(守则情况)','542','jdbcamway',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('201317','Local_Business','Local Business(本地市场)','542','jdbcamway',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('201318','Donation_Record_Edit','ACF Donation Record(ACF捐款情况)','542','jdbcamway',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('201319','Philanthropic_Activity','Significant Philanthropic Activity(其他慈善活动参与情况)','542','jdbcamway',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('201320','Local_Business_Edit','Local Business(本地市场)','542','jdbcamway',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('201321','Recognition','Recognition(表扬情况)','542','jdbcamway',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('201322','Business_Oversea','Business Overseas(海外市场)','542','jdbcamway',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
;
INSERT INTO test.mstb_query_index (QUERY_ID,QUERY_CODE,QUERY_NAME,APPLICATION_ID,DS_JNDI,IS_COL_HEA_FIL,EXTERNAL_JS,IS_DEFAULT_QRY,GLOBAL_WHERE,REMARE,USE_STATE,RECORD_STATE,CREATED_USER_ID,CREATED_TIME,UPDATED_USER_ID,UPDATED_TIME,IS_REFRESH) VALUES 
('201323','Personal_Info','Personal Info.(个人基本信息)','542','jdbcamway',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('201324','Health_Family','Health & Family(健康状况及家庭)','542','jdbcamway',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('201325','Treatment_Edit','Treatment(福利待遇)','542','jdbcamway',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('201326','Distributor_Info','Distributor Info(户籍基本信息)','542','jdbcamway',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('201327','Children_Info','Children info(子女信息)','542','jdbcamway',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('201328','Business_Oversea_Edit','Business Overseas(海外市场)','542','jdbcamway',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('201329','Donation_Record','ACF Donation Record(ACF捐款情况)','542','jdbcamway',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('201330','Children_Info_Edit','Children info(子女信息)','542','jdbcamway',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('201331','Business_Data','Business Data (业务概况)','542','jdbcamway',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('201332','Philanthropic_Activity_Edit','Significant Philanthropic Activity(其他慈善活动参与情况)','542','jdbcamway',1,NULL,1,NULL,'编辑活动列表',1,1,NULL,NULL,NULL,NULL,1)
;
INSERT INTO test.mstb_query_index (QUERY_ID,QUERY_CODE,QUERY_NAME,APPLICATION_ID,DS_JNDI,IS_COL_HEA_FIL,EXTERNAL_JS,IS_DEFAULT_QRY,GLOBAL_WHERE,REMARE,USE_STATE,RECORD_STATE,CREATED_USER_ID,CREATED_TIME,UPDATED_USER_ID,UPDATED_TIME,IS_REFRESH) VALUES 
('201333','Other_Activity','Other_ Activity 其他慈善机构情况','542','jdbcamway',1,NULL,1,NULL,NULL,0,1,NULL,NULL,NULL,NULL,1)
,('201334','Global_Recogniton_Edit','Global Recogniton 美国总部表扬情况','542','jdbcamway',1,NULL,1,NULL,NULL,0,1,NULL,NULL,NULL,NULL,1)
,('201335','System_Log','System Log','542','jdbcamway',1,NULL,1,NULL,'系统日志',1,1,NULL,NULL,NULL,NULL,1)
,('201336','FC_ROLEUSER','角色分配用户','542','jdbcamway',0,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('201341','Treatment','Treatment(福利待遇)','542','jdbcamway',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('201342','Recognition_Edit','Recognition(表扬情况)','542','jdbcamway',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('201343','FC_DST_USER','查询同步用户','542','jdbcamway',1,NULL,0,NULL,NULL,1,1,NULL,NULL,NULL,NULL,0)
,('201344','FC_DST_ADDRESS','同步地址表','542','jdbcamway',1,NULL,0,NULL,NULL,1,1,NULL,NULL,NULL,NULL,0)
,('201345','FC_DST_EMAIL','同步EMAIL','542','jdbcamway',1,NULL,0,NULL,NULL,1,1,NULL,NULL,NULL,NULL,0)
,('201346','FC_DST_PHONE','同步电话','542','jdbcamway',1,NULL,0,NULL,NULL,1,1,NULL,NULL,NULL,NULL,0)
;
INSERT INTO test.mstb_query_index (QUERY_ID,QUERY_CODE,QUERY_NAME,APPLICATION_ID,DS_JNDI,IS_COL_HEA_FIL,EXTERNAL_JS,IS_DEFAULT_QRY,GLOBAL_WHERE,REMARE,USE_STATE,RECORD_STATE,CREATED_USER_ID,CREATED_TIME,UPDATED_USER_ID,UPDATED_TIME,IS_REFRESH) VALUES 
('201347','mt_listDetailShop_bak20140307','销售收入明细表视图(店铺)','121','jdbcamway',1,NULL,1,NULL,'会议门券销售收入明细表视图(店铺)',1,1,NULL,NULL,NULL,NULL,1)
,('2164','dst_user','同步人员信息','401','jdbcamway',1,NULL,0,NULL,NULL,1,1,NULL,NULL,NULL,NULL,0)
,('2167','DST_TRAIN_INFO','同步培训情况','401','jdbcamway',1,NULL,0,NULL,NULL,1,1,NULL,NULL,NULL,NULL,0)
,('2168','DST_RULES_INFO','同步守则情况','401','jdbcamway',1,NULL,0,NULL,NULL,1,1,NULL,NULL,NULL,NULL,0)
,('2187','smt_report_five','AA代征发票查询','301','jdbcamway',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('223','checkReturn_shop','待办流程','101','jdbcamway',1,NULL,1,'(${formState} or ${formState2} )',NULL,1,1,NULL,NULL,NULL,NULL,1)
,('241','afw_userProfile','用户信息维护','1','jdbcamway',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('261','sysManage_smsTemplate','短信模板配置','1','jdbcamway',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('262','checkReturn_comm_query','自定义查询','101','jdbcamway',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('281','checkReturn_bankAccount','付款银行账号维护','101','jdbcamway',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
;
INSERT INTO test.mstb_query_index (QUERY_ID,QUERY_CODE,QUERY_NAME,APPLICATION_ID,DS_JNDI,IS_COL_HEA_FIL,EXTERNAL_JS,IS_DEFAULT_QRY,GLOBAL_WHERE,REMARE,USE_STATE,RECORD_STATE,CREATED_USER_ID,CREATED_TIME,UPDATED_USER_ID,UPDATED_TIME,IS_REFRESH) VALUES 
('282','checkReturn_shopCoda','入账银行CODA代码维护','101','jdbcamway',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('301','mt_financeBacklog','待办流程','121','jdbcamway',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('321','log_operation','操作日志','1','jdbcamway',1,NULL,0,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('322','log_performance','性能日志','1','jdbcamway',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('323','email_send_record','邮件记录','1','jdbcamway',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('342','test','测试查询','1','jdbcamway',0,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('361','mt_shopBacklog','待办流程','121','jdbcamway',1,NULL,1,'(${formState} or ${formState1})',NULL,1,1,NULL,NULL,NULL,NULL,1)
,('381','mt_listDetail','销售收入明细表视图','121','jdbcamway',1,NULL,1,NULL,'会议门券销售收入明细表视图',1,1,NULL,NULL,NULL,NULL,1)
,('383','checkReturn_finance','待办流程','101','jdbcamway',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('401','mt_listStatistics','销售收入明细表统计','121','jdbcamway',1,NULL,1,'(${formState}or ${formState1})','会议门券销售收入明细表统计',1,1,NULL,NULL,NULL,NULL,1)
;
INSERT INTO test.mstb_query_index (QUERY_ID,QUERY_CODE,QUERY_NAME,APPLICATION_ID,DS_JNDI,IS_COL_HEA_FIL,EXTERNAL_JS,IS_DEFAULT_QRY,GLOBAL_WHERE,REMARE,USE_STATE,RECORD_STATE,CREATED_USER_ID,CREATED_TIME,UPDATED_USER_ID,UPDATED_TIME,IS_REFRESH) VALUES 
('402','mt_listDetailShop','销售收入明细表视图(店铺)','121','jdbcamway',1,NULL,1,NULL,'会议门券销售收入明细表视图(店铺)',1,1,NULL,NULL,NULL,NULL,1)
,('403','addedTax_shop','待办流程','201','jdbcamway',1,NULL,1,'(${formState} or ${formState2} )',NULL,1,1,NULL,NULL,NULL,NULL,1)
,('404','sysManage_report','定时报表设置','1','jdbcamway',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('405','report_sql','报表语句设置','1','jdbcamway',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('406','report_para','报表参数设置','1','jdbcamway',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('408','ib_shopBacklog','待办流程','203','jdbcamway',1,NULL,1,'(${formState1} or ${formState2} )',NULL,1,1,NULL,NULL,NULL,NULL,1)
,('41','03','异常管理','1','jdbcamway',1,'http://localhost:8080/exception/exception.js',1,NULL,'fff111',1,1,NULL,NULL,NULL,NULL,1)
,('422','ib_invoiceBalanceStat','店铺缴税专户余款统计视图','203','jdbcamway',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('423','ib_invoiceBalanceShopQueryView','店铺缴税专户余款视图(店铺)','203','jdbcamway',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('424','ib_financeBacklog','待办流程','203','jdbcamway',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
;
INSERT INTO test.mstb_query_index (QUERY_ID,QUERY_CODE,QUERY_NAME,APPLICATION_ID,DS_JNDI,IS_COL_HEA_FIL,EXTERNAL_JS,IS_DEFAULT_QRY,GLOBAL_WHERE,REMARE,USE_STATE,RECORD_STATE,CREATED_USER_ID,CREATED_TIME,UPDATED_USER_ID,UPDATED_TIME,IS_REFRESH) VALUES 
('425','addedTax_finance','待办流程','201','jdbcamway',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('426','ib_invoiceBalanceFinanceQueryView','店铺缴税专户余款视图(财务)','203','jdbcamway',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('427','addedTax_confirmView','增值税发票抵扣联确认的视图','201','jdbcamway',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('428','addedTax_InfoView','增值税发票抵扣联信息视图','201','jdbcamway',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('441','shopAuthList','店铺报表权限视图','221','jdbcamway',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('442','ebooking_myManagerMeeting','我管理的会议','21','jdbcamway',1,NULL,1,'(${isEbookingAdmin} or ${empNumber})',NULL,1,1,NULL,NULL,NULL,NULL,1)
,('461','testGroupBy','添加GROUP记录','221','jdbcamway',0,'query/common/js/test.js',0,NULL,'使用GROUPBY表，这样导数据时方便',1,1,NULL,NULL,NULL,NULL,1)
,('504','sysManage_job','定时任务配置','1','jdbcamway',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('541','si_shopBacklog','待办流程','241','jdbcamway',1,NULL,1,'(${formState} or ${formState1})',NULL,1,1,NULL,NULL,NULL,NULL,1)
,('542','si_financeBacklog','待办流程','241','jdbcamway',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
;
INSERT INTO test.mstb_query_index (QUERY_ID,QUERY_CODE,QUERY_NAME,APPLICATION_ID,DS_JNDI,IS_COL_HEA_FIL,EXTERNAL_JS,IS_DEFAULT_QRY,GLOBAL_WHERE,REMARE,USE_STATE,RECORD_STATE,CREATED_USER_ID,CREATED_TIME,UPDATED_USER_ID,UPDATED_TIME,IS_REFRESH) VALUES 
('561','ft_shopBacklog','待办流程','261','jdbcamway',1,NULL,1,'(${formState1} or ${formState2} )',NULL,1,1,NULL,NULL,NULL,NULL,1)
,('562','ft_financeBacklog','待办流程','261','jdbcamway',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('563','ft_statQuery','财务税务资料核对统计视图','261','jdbcamway',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('564','ft_shopQueryView','财务税务资料核对视图(店铺)','261','jdbcamway',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('565','ft_financeQueryView','财务税务资料核对视图(财务)','261','jdbcamway',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('566','ft_joinMeetingQuery','每月反馈参加税务部门会议信息','261','jdbcamway',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('581','ib_bankList','银行代码维护','203','jdbcamway',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('601','si_listStatistics','店铺发票统计视图','241','jdbcamway',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('621','si_listDetailShop','店铺发票视图(店铺)','241','jdbcamway',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('622','si_listDetail','店铺发票视图(财务)','241','jdbcamway',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
;
INSERT INTO test.mstb_query_index (QUERY_ID,QUERY_CODE,QUERY_NAME,APPLICATION_ID,DS_JNDI,IS_COL_HEA_FIL,EXTERNAL_JS,IS_DEFAULT_QRY,GLOBAL_WHERE,REMARE,USE_STATE,RECORD_STATE,CREATED_USER_ID,CREATED_TIME,UPDATED_USER_ID,UPDATED_TIME,IS_REFRESH) VALUES 
('641','smt_todo','待办流程','301','jdbcamway',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('642','smt_fin_todo','待办流程','301','jdbcamway',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('654','smt_finish_submit','查看过往提交的汇总表','301','jdbcamway',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('661','smt_report_one','应交税款(表一)','301','jdbcamway',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('662','smt_report_two','应交税款(表二)','301','jdbcamway',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('663','smt_report_three','应交税款(表三)','301','jdbcamway',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('664','smt_report_four','应交税款(表四)','301','jdbcamway',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('681','sysManage_smsLog','短信记录','1','jdbcamway',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('701','smt_bankList','应提交店铺列表','301','jdbcamway',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('721','TestSelect','系统用户列表','401','jdbcamway',0,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
;
INSERT INTO test.mstb_query_index (QUERY_ID,QUERY_CODE,QUERY_NAME,APPLICATION_ID,DS_JNDI,IS_COL_HEA_FIL,EXTERNAL_JS,IS_DEFAULT_QRY,GLOBAL_WHERE,REMARE,USE_STATE,RECORD_STATE,CREATED_USER_ID,CREATED_TIME,UPDATED_USER_ID,UPDATED_TIME,IS_REFRESH) VALUES 
('722','mt_shopBacklogForDraft','待办流程','121','jdbcamway',1,NULL,1,'(${empNumber}or ${createUser})',NULL,1,1,NULL,NULL,NULL,NULL,1)
,('741','praise_roleUser','角色分配用户','401','jdbcamway',0,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('761','TEST_HSTB_PRA_QUALIFY','TEST_HSTB_PRA_QUALIFY','401','jdbcamway',0,NULL,0,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('781','CFG_PIN','职级管理','401','jdbcamway',0,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('782','CFG_PIN_RELEVANCE','已绑定职级列表','401','jdbcamway',0,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('801','CFG_PRAISE_TYPE','表扬类型管理','401','jdbcamway',0,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('802','CFG_PRAISE_TYPE_PROJECT','表扬项目管理 ','401','jdbcamway',0,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('80201350','hk_user_manage_query','HK User Query','80200522','jdbcamwayAmanet',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('80201351','hk_change_pwd_log','HK Change Password Log','80200522','jdbcamwayAmanet',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('80201352','hk_alternate_address_query','HK_Alternate_Address_Query','80200522','jdbcamwayAmanet',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
;
INSERT INTO test.mstb_query_index (QUERY_ID,QUERY_CODE,QUERY_NAME,APPLICATION_ID,DS_JNDI,IS_COL_HEA_FIL,EXTERNAL_JS,IS_DEFAULT_QRY,GLOBAL_WHERE,REMARE,USE_STATE,RECORD_STATE,CREATED_USER_ID,CREATED_TIME,UPDATED_USER_ID,UPDATED_TIME,IS_REFRESH) VALUES 
('803','CFG_PRAISE_CONTENT','表扬项目内容管理','401','jdbcamway',0,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('804','CFG_WELFARE','福利管理','401','jdbcamway',0,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('805','GDS_GOODS_COMPONENT','组件管理 ','401','jdbcamway',0,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('806','GDS_GOODS','物品管理','401','jdbcamway',0,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('807','GDS_GOODS_BINDIND','已绑定组件列表','401','jdbcamway',0,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('81','02','功能信息维护','1','jdbcamway',1,NULL,0,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('82','ebooking_blacklist','黑名单','21','jdbcamway',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('8201313','signup_query','new signup info query','8200528','jdbcamwayAmanet',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('821','GDS_WAREHOUSE_IN','入仓管理','401','jdbcamway',0,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('822','PRAISE_LIST_STAR','表扬名单','401','jdbcamway',0,'/amway-praise/static/js/praise_list/confirmPraiseList.js',1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
;
INSERT INTO test.mstb_query_index (QUERY_ID,QUERY_CODE,QUERY_NAME,APPLICATION_ID,DS_JNDI,IS_COL_HEA_FIL,EXTERNAL_JS,IS_DEFAULT_QRY,GLOBAL_WHERE,REMARE,USE_STATE,RECORD_STATE,CREATED_USER_ID,CREATED_TIME,UPDATED_USER_ID,UPDATED_TIME,IS_REFRESH) VALUES 
('823','GDS_WAREHOUSE_ASSIGN','物品分配','401','jdbcamway',0,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('824','GDS_WAREHOUSE_LOSS','物品损耗','401','jdbcamway',0,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('825','GDS_WAREHOUSE','库存查询','401','jdbcamway',0,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('841','GDS_WAREHOUSE_OUT','表扬物品领取','401','jdbcamway',0,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('842','PRAISE_LIST_POST','表扬名单','401','jdbcamway',0,'/amway-praise/static/js/praise_list/confirmPraiseList.js',1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('861','QUALIFY_SEARCH','认承名单查询','401','jdbcamway',0,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('862','DST_PICTURE_MANAGE','照片登记情况列表 ','401','jdbcamway',0,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('863','PRAISE_LIST_SEARCH','表扬名单查询','401','jdbcamway',0,'/amway-praise/static/js/praise_list/deletePraiseList.js',1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('864','DST_PUBLISH_DESIRE','营销人员声明情况查询','401','jdbcamway',0,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('881','NOT_PRAISE_LIST_SEARCH','不表扬名单查询','401','jdbcamway',0,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
;
INSERT INTO test.mstb_query_index (QUERY_ID,QUERY_CODE,QUERY_NAME,APPLICATION_ID,DS_JNDI,IS_COL_HEA_FIL,EXTERNAL_JS,IS_DEFAULT_QRY,GLOBAL_WHERE,REMARE,USE_STATE,RECORD_STATE,CREATED_USER_ID,CREATED_TIME,UPDATED_USER_ID,UPDATED_TIME,IS_REFRESH) VALUES 
('882','PRA_PRAISE_LIST_INIT','表扬榜初稿查询','401','jdbcamway',0,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('88201320','docflow_list','由我创建','88200545','jdbcamway',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('88201321','docflow_list_prouser','我的待办(处理人)','88200545','jdbcamway',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('88201322','docflow_list_myself','经我办理','88200545','jdbcamway',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('88201323','docflow_list_genuser','我的待办(申请人)','88200545','jdbcamway',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('88201324','docflow_list_draft','我的草稿','88200545','jdbcamway',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('88201347','doc_list_custom_query','自定义查询','88200545','jdbcamway',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('88201349','doc_list_custom_query_admin','自定义查询(管理员)','88200545','jdbcamway',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('883','NOMINATE_SEARCH','题名类查询','401','jdbcamway',0,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('884','MEETING_SEARCH','会议类查询','401','jdbcamway',0,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
;
INSERT INTO test.mstb_query_index (QUERY_ID,QUERY_CODE,QUERY_NAME,APPLICATION_ID,DS_JNDI,IS_COL_HEA_FIL,EXTERNAL_JS,IS_DEFAULT_QRY,GLOBAL_WHERE,REMARE,USE_STATE,RECORD_STATE,CREATED_USER_ID,CREATED_TIME,UPDATED_USER_ID,UPDATED_TIME,IS_REFRESH) VALUES 
('885','PRA_PRAISE_LIST_FINAL','表扬榜终稿查询','401','jdbcamway',0,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('887','PRA_PRAISE_LIST_INIT_DRAFT','待确认表扬榜初稿','401','jdbcamway',0,'/amway-praise/static/js/month_praise_list/praiseList.js',1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,0)
,('888','PRA_PRAISE_LIST_FINAL_DRAFT','待确认表扬榜终稿','401','jdbcamway',0,'/amway-praise/static/js/month_praise_list/praiseList.js',1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('889','OTHER_SEARCH','其它表扬执行查询','401','jdbcamway',0,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('890','PRA_GRADING_IMPORT','定级名单导入','401','jdbcamway',0,'/amway-praise/static/js/praise_year/praGradingImport.js',1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('891','WELFARE_SEARCH','福利查询','401','jdbcamway',0,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('892','PRA_GRADING','定级名单查询 ','401','jdbcamway',0,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('901','SYSTME_USER_MANAGE','用户信息维护','401','jdbcamway',0,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('921','PRA_PRAISE_INIT','营销助理/主任/高主/助经表扬名单','401','jdbcamway',0,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,0)
,('941','CFG_PIN_LIST','职级列表','401','jdbcamway',0,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
;
INSERT INTO test.mstb_query_index (QUERY_ID,QUERY_CODE,QUERY_NAME,APPLICATION_ID,DS_JNDI,IS_COL_HEA_FIL,EXTERNAL_JS,IS_DEFAULT_QRY,GLOBAL_WHERE,REMARE,USE_STATE,RECORD_STATE,CREATED_USER_ID,CREATED_TIME,UPDATED_USER_ID,UPDATED_TIME,IS_REFRESH) VALUES 
('981','SENDER_EMAIL_SETTING','发送邮件设置','401','jdbcamway',0,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('99201347','cad_draftList','草稿','99200522','jdbcamway',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('99201348','cad_gEmpManagerList','员工授权管理','99200522','jdbcamway',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('99201349','cad_submitedList','已提交','99200522','jdbcamway',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('99201350','cad_submitedList_Fc','已提交','99200522','jdbcamway',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
,('99201351','cad_readUserList','读者信息维护','99200522','jdbcamway',1,NULL,1,NULL,NULL,1,1,NULL,NULL,NULL,NULL,1)
;